Repository microsoft/fast, pull requests merged in 2018-08, with the labels that each got.

#724 feat(fast-development-site): update waffle menu style and animations
  packages/fast-development-site-react/src/components/shell/header.tsx
  packages/fast-development-site-react/src/components/site/index.tsx
  packages/fast-development-site-react/src/components/site/menu.tsx
Labels: pr : feature

#751 feat(colors): add contrast and luminosity utilities
  packages/fast-colors/README.md
  packages/fast-colors/package-lock.json
  packages/fast-colors/package.json
  packages/fast-colors/src/contrast.spec.ts
  packages/fast-colors/src/contrast.ts
  packages/fast-colors/src/index.ts
  packages/fast-colors/src/luminosity.spec.ts
  packages/fast-colors/src/luminosity.ts
Labels: pr : feature

#752 feat(dialog): add dialog as a new component
  packages/fast-components-class-name-contracts-base/src/dialog/index.ts
  packages/fast-components-class-name-contracts-base/src/index.ts
  packages/fast-components-react-base/app/examples.ts
  packages/fast-components-react-base/src/dialog/README.md
  packages/fast-components-react-base/src/dialog/__snapshots__/dialog.spec.tsx.snap
  packages/fast-components-react-base/src/dialog/dialog.props.ts
  packages/fast-components-react-base/src/dialog/dialog.schema.json
  packages/fast-components-react-base/src/dialog/dialog.spec.tsx
  packages/fast-components-react-base/src/dialog/dialog.tsx
  packages/fast-components-react-base/src/dialog/examples.data.tsx
  packages/fast-components-react-base/src/dialog/index.ts
  packages/fast-components-react-base/src/index.ts
  packages/fast-components-react-msft/app/examples.ts
  packages/fast-components-react-msft/src/dialog/README.md
  packages/fast-components-react-msft/src/dialog/__snapshots__/dialog.spec.ts.snap
  packages/fast-components-react-msft/src/dialog/dialog.spec.ts
  packages/fast-components-react-msft/src/dialog/examples.data.tsx
  packages/fast-components-react-msft/src/dialog/index.ts
  packages/fast-components-react-msft/src/index.ts
  packages/fast-components-styles-msft/src/dialog/index.ts
  packages/fast-components-styles-msft/src/index.ts
  packages/fast-components-styles-msft/src/utilities/acrylic.ts
Labels: pr : feature

#754 chore(fast-components-react-msft): fix incorrect web address in documentation in readme
  packages/fast-components-react-msft/README.md
Labels: pr : chore

#745 feat(fast-development-site): add hover and focus states to TOC menu items
  packages/fast-development-site-react/src/components/toc/toc-item.tsx
  packages/fast-development-site-react/src/components/toc/toc-menu.tsx
Labels: pr : feature

#755 fix(label): fix spelling error in interface name for managed classes
  packages/fast-components-react-base/src/label/examples.data.tsx
  packages/fast-components-react-base/src/label/label.props.ts
  packages/fast-components-react-base/src/label/label.spec.tsx
  packages/fast-components-react-base/src/label/label.tsx
Labels: pr : breaking change :boom:

#748 feat(fast-development-site): add hover and focus states to action bar items
  packages/fast-development-site-react/src/components/site/action-bar.tsx
  packages/fast-development-site-react/src/components/site/component-view-toggle.tsx
  packages/fast-development-site-react/src/components/site/configuration-panel.tsx
Labels: pr : feature

#760 fix(fast-form-generator): alignment of fast form children text and glyph
  packages/fast-form-generator-react/src/form/form-item.children.style.ts
Labels: pr : fix

#708 feat(fast-form-generator): add logic to close option menus when clicking outside of menu UI
  packages/fast-form-generator-react/package-lock.json
  packages/fast-form-generator-react/package.json
  packages/fast-form-generator-react/src/form/form-item.array.tsx
  packages/fast-form-generator-react/src/form/form-item.children.tsx
Labels: pr : feature

#767 fix(fast-web-utilities): fix an issue where getClientRectWithMargin threw an error in EDGE and IE strict modes due to readonly properties
  packages/fast-web-utilities/src/html.ts
Labels: pr : fix

#765 feat(fast-development-site-react): add enums for tabType for better type safety and clarity
  packages/fast-development-site-react/app/app.tsx
  packages/fast-development-site-react/src/components/site/dev-tools-code-preview.tsx
  packages/fast-development-site-react/src/components/site/dev-tools.tsx
  packages/fast-development-site-react/src/components/site/index.tsx
Labels: pr : feature

#769 fix(hyperlink): correctly handle href as a handled prop and update documentation
  packages/fast-components-react-base/src/hypertext/README.md
  packages/fast-components-react-base/src/hypertext/hypertext.tsx
  packages/fast-components-react-msft/src/hypertext/README.md
  packages/fast-components-react-msft/src/hypertext/__snapshots__/hypertext.spec.ts.snap
Labels: pr : fix

#773 chore(components): update readme files to reference component name as h1
  packages/fast-components-react-base/src/button/README.md
  packages/fast-components-react-base/src/checkbox/README.md
  packages/fast-components-react-base/src/dialog/README.md
  packages/fast-components-react-base/src/divider/README.md
  packages/fast-components-react-base/src/horizontal-overflow/README.md
  packages/fast-components-react-base/src/image/README.MD
  packages/fast-components-react-base/src/image/README.md
  packages/fast-components-react-base/src/label/README.MD
  packages/fast-components-react-base/src/label/README.md
  packages/fast-components-react-base/src/tabs/README.md
  packages/fast-components-react-base/src/text-field/README.md
  packages/fast-components-react-base/src/toggle/README.md
  packages/fast-components-react-base/src/typography/README.md
  packages/fast-components-react-msft/src/button/README.md
  packages/fast-components-react-msft/src/checkbox/README.md
  packages/fast-components-react-msft/src/dialog/README.md
  packages/fast-components-react-msft/src/divider/README.md
  packages/fast-components-react-msft/src/flipper/README.md
  packages/fast-components-react-msft/src/heading/README.md
  packages/fast-components-react-msft/src/image/README.md
  packages/fast-components-react-msft/src/label/README.md
  packages/fast-components-react-msft/src/text-field/README.md
  packages/fast-components-react-msft/src/toggle/README.md
  packages/fast-components-react-msft/src/typography/README.md
Labels: pr : chore

#775 chore(build): fix build break due to incorrect lerna version install
  .circleci/config.yml
Labels: pr : chore

#780 docs(fast-components-react-base): add accessibility documentation and core documentation clean up
  packages/fast-components-react-base/src/button/README.md
  packages/fast-components-react-base/src/checkbox/README.md
  packages/fast-components-react-base/src/dialog/README.md
  packages/fast-components-react-base/src/divider/README.md
  packages/fast-components-react-base/src/horizontal-overflow/README.md
  packages/fast-components-react-base/src/image/README.md
  packages/fast-components-react-base/src/label/README.md
  packages/fast-components-react-base/src/text-field/README.md
  packages/fast-components-react-base/src/toggle/README.md
Labels: pr : docs

#783 fix(fast-components-react-base): allow horizontal overflow to accept passed class names
  packages/fast-components-react-base/src/horizontal-overflow/__snapshots__/horizontal-overflow.spec.tsx.snap
  packages/fast-components-react-base/src/horizontal-overflow/examples.data.tsx
  packages/fast-components-react-base/src/horizontal-overflow/horizontal-overflow.tsx
Labels: pr : fix

#795 feat: update Lerna to ^3.0.0
  .circleci/config.yml
  lerna.json
  package-lock.json
  package.json
  packages/fast-animation/package-lock.json
  packages/fast-animation/package.json
  packages/fast-application-utilities/package-lock.json
  packages/fast-application-utilities/package.json
  packages/fast-browser-extensions/package-lock.json
  packages/fast-browser-extensions/package.json
  packages/fast-colors/package-lock.json
  packages/fast-colors/package.json
  packages/fast-components-class-name-contracts-base/package-lock.json
  packages/fast-components-class-name-contracts-base/package.json
  packages/fast-components-class-name-contracts-msft/package-lock.json
  packages/fast-components-class-name-contracts-msft/package.json
  packages/fast-components-react-base/package-lock.json
  packages/fast-components-react-base/package.json
  packages/fast-components-react-msft/package-lock.json
  packages/fast-components-react-msft/package.json
  packages/fast-components-styles-msft/package-lock.json
  packages/fast-components-styles-msft/package.json
  packages/fast-css-editor-react/package-lock.json
  packages/fast-css-editor-react/package.json
  packages/fast-development-site-react/package-lock.json
  packages/fast-development-site-react/package.json
  packages/fast-form-generator-react/package-lock.json
  packages/fast-form-generator-react/package.json
  packages/fast-glyphs-msft/package-lock.json
  packages/fast-glyphs-msft/package.json
  packages/fast-jest-snapshots-react/package-lock.json
  packages/fast-jest-snapshots-react/package.json
  packages/fast-jss-manager-angular/package-lock.json
  packages/fast-jss-manager-angular/package.json
  packages/fast-jss-manager-react/package-lock.json
  packages/fast-jss-manager-react/package.json
  packages/fast-jss-manager/package-lock.json
  packages/fast-jss-manager/package.json
  packages/fast-jss-utilities/package-lock.json
  packages/fast-jss-utilities/package.json
  packages/fast-layouts-react/package-lock.json
  packages/fast-layouts-react/package.json
  packages/fast-markdown-msft-react/package-lock.json
  packages/fast-markdown-msft-react/package.json
  packages/fast-permutator/package-lock.json
  packages/fast-sketch-library/package-lock.json
  packages/fast-sketch-library/package.json
  packages/fast-tslint-rules/package-lock.json
  packages/fast-tslint-rules/package.json
  packages/fast-viewer-react/package-lock.json
  packages/fast-viewer-react/package.json
  packages/fast-web-utilities/package-lock.json
  packages/fast-web-utilities/package.json
Labels: pr : chore

#800 fix(fast-form-generator-react): fix form item select to return the correct value based on type
  packages/fast-form-generator-react/app/components/number-field/__snapshots__/number-field.spec.tsx.snap
  packages/fast-form-generator-react/app/components/text-field/__snapshots__/text-field.spec.tsx.snap
  packages/fast-form-generator-react/app/components/weight-properties/__snapshots__/weight-properties.spec.tsx.snap
  packages/fast-form-generator-react/src/form/form-item.select.tsx
Labels: pr : fix

#805 feat(paragraph): adds paragraph as a new MSFT component
  packages/fast-application-utilities/package-lock.json
  packages/fast-browser-extensions/package-lock.json
  packages/fast-colors/package-lock.json
  packages/fast-components-class-name-contracts-msft/src/index.ts
  packages/fast-components-class-name-contracts-msft/src/paragraph/index.ts
  packages/fast-components-react-base/package-lock.json
  packages/fast-components-react-msft/app/examples.ts
  packages/fast-components-react-msft/package-lock.json
  packages/fast-components-react-msft/src/heading/README.md
  packages/fast-components-react-msft/src/paragraph/README.md
  packages/fast-components-react-msft/src/paragraph/__snapshots__/paragraph.spec.tsx.snap
  packages/fast-components-react-msft/src/paragraph/examples.data.tsx
  packages/fast-components-react-msft/src/paragraph/index.ts
  packages/fast-components-react-msft/src/paragraph/paragraph.props.ts
  packages/fast-components-react-msft/src/paragraph/paragraph.schema.json
  packages/fast-components-react-msft/src/paragraph/paragraph.spec.tsx
  packages/fast-components-react-msft/src/paragraph/paragraph.tsx
  packages/fast-components-styles-msft/src/index.ts
  packages/fast-components-styles-msft/src/paragraph/index.ts
  packages/fast-css-editor-react/package-lock.json
  packages/fast-development-site-react/package-lock.json
  packages/fast-form-generator-react/package-lock.json
  packages/fast-jest-snapshots-react/package-lock.json
  packages/fast-jss-manager-angular/package-lock.json
  packages/fast-jss-manager-react/package-lock.json
  packages/fast-jss-utilities/package-lock.json
  packages/fast-layouts-react/package-lock.json
  packages/fast-markdown-msft-react/package-lock.json
  packages/fast-sketch-library/package-lock.json
  packages/fast-tslint-rules/package-lock.json
  packages/fast-viewer-react/package-lock.json
  packages/fast-web-utilities/package-lock.json
Labels: pr : feature

#808 fix(foundation): ensures that children are never rendered to the root element by unhandledProps
  packages/fast-components-react-base/src/button/button.tsx
  packages/fast-components-react-base/src/dialog/dialog.tsx
  packages/fast-components-react-base/src/foundation/foundation.spec.tsx
  packages/fast-components-react-base/src/foundation/foundation.ts
  packages/fast-components-react-base/src/horizontal-overflow/horizontal-overflow.tsx
  packages/fast-components-react-base/src/hypertext/hypertext.tsx
  packages/fast-components-react-base/src/label/label.tsx
  packages/fast-components-react-base/src/tabs/tab-panel.tsx
  packages/fast-components-react-base/src/tabs/tab.tsx
  packages/fast-components-react-base/src/tabs/tabs.tsx
  packages/fast-components-react-msft/src/button/button.tsx
Labels: pr : fix

#814 chore: update fast-animation's TypeScript
  packages/fast-animation/__tests__/index.ts
  packages/fast-animation/client/examples/app/components/TestPage.tsx
  packages/fast-animation/lib/animate/index.ts
  packages/fast-animation/lib/animateGroup/index.ts
  packages/fast-animation/lib/fade/index.ts
  packages/fast-animation/lib/tsconfig.json
  packages/fast-animation/package-lock.json
  packages/fast-animation/package.json
  packages/fast-animation/tsconfig.json
Labels: pr : chore

#797 feat(fast-components-react-base): add callback to horizontal overflow to return and object that informs scroll start and end
  package-lock.json
  packages/fast-animation/package-lock.json
  packages/fast-application-utilities/package-lock.json
  packages/fast-browser-extensions/package-lock.json
  packages/fast-colors/package-lock.json
  packages/fast-components-class-name-contracts-base/package-lock.json
  packages/fast-components-class-name-contracts-msft/package-lock.json
  packages/fast-components-react-base/package-lock.json
  packages/fast-components-react-base/package.json
  packages/fast-components-react-base/src/horizontal-overflow/README.md
  packages/fast-components-react-base/src/horizontal-overflow/horizontal-overflow.props.ts
  packages/fast-components-react-base/src/horizontal-overflow/horizontal-overflow.spec.tsx
  packages/fast-components-react-base/src/horizontal-overflow/horizontal-overflow.tsx
  packages/fast-components-react-msft/package-lock.json
  packages/fast-components-styles-msft/package-lock.json
  packages/fast-css-editor-react/package-lock.json
  packages/fast-development-site-react/package-lock.json
  packages/fast-form-generator-react/package-lock.json
  packages/fast-glyphs-msft/package-lock.json
  packages/fast-jest-snapshots-react/package-lock.json
  packages/fast-jss-manager-angular/package-lock.json
  packages/fast-jss-manager-react/package-lock.json
  packages/fast-jss-manager/package-lock.json
  packages/fast-jss-utilities/package-lock.json
  packages/fast-layouts-react/package-lock.json
  packages/fast-markdown-msft-react/package-lock.json
  packages/fast-permutator/package-lock.json
  packages/fast-sketch-library/package-lock.json
  packages/fast-tslint-rules/package-lock.json
  packages/fast-viewer-react/package-lock.json
  packages/fast-web-utilities/package-lock.json
Labels: pr : feature

#816 feat(fast-development-site-react): add component example transparency as opt-out
  packages/fast-components-react-base/app/index.tsx
  packages/fast-components-react-msft/app/app.tsx
  packages/fast-development-site-react/app/app.tsx
  packages/fast-development-site-react/src/components/site/index.tsx
Labels: pr : feature

#810 feat: add contrast based color system
  packages/fast-animation/package-lock.json
  packages/fast-application-utilities/package-lock.json
  packages/fast-browser-extensions/package-lock.json
  packages/fast-colors/.babelrc
  packages/fast-colors/.npmignore
  packages/fast-colors/package-lock.json
  packages/fast-colors/package.json
  packages/fast-colors/src/contrast.spec.ts
  packages/fast-colors/src/contrast.ts
  packages/fast-colors/src/index.ts
  packages/fast-colors/src/luminosity.ts
  packages/fast-components-class-name-contracts-base/package-lock.json
  packages/fast-components-class-name-contracts-msft/package-lock.json
  packages/fast-components-class-name-contracts-msft/src/button/index.ts
  packages/fast-components-react-base/package-lock.json
  packages/fast-components-react-base/src/button/button.tsx
  packages/fast-components-react-msft/package-lock.json
  packages/fast-components-react-msft/src/button/__snapshots__/button.spec.tsx.snap
  packages/fast-components-react-msft/src/button/examples.data.tsx
  packages/fast-components-styles-msft/package-lock.json
  packages/fast-components-styles-msft/src/button/index.ts
  packages/fast-components-styles-msft/src/checkbox/index.ts
  packages/fast-components-styles-msft/src/design-system/index.ts
  packages/fast-components-styles-msft/src/dialog/index.ts
  packages/fast-components-styles-msft/src/divider/index.ts
  packages/fast-components-styles-msft/src/flipper/index.ts
  packages/fast-components-styles-msft/src/hypertext/index.ts
  packages/fast-components-styles-msft/src/label/index.ts
  packages/fast-components-styles-msft/src/text-field/index.ts
  packages/fast-components-styles-msft/src/toggle/index.ts
  packages/fast-components-styles-msft/src/typography/index.ts
  packages/fast-components-styles-msft/src/utilities/colors.ts
  packages/fast-css-editor-react/app/app.tsx
  packages/fast-css-editor-react/app/components/editor.spec.tsx
  packages/fast-css-editor-react/app/components/position.spec.tsx
  packages/fast-css-editor-react/package-lock.json
  packages/fast-development-site-react/package-lock.json
  packages/fast-form-generator-react/package-lock.json
  packages/fast-glyphs-msft/package-lock.json
  packages/fast-jest-snapshots-react/package-lock.json
  packages/fast-jss-manager-angular/package-lock.json
  packages/fast-jss-manager-react/package-lock.json
  packages/fast-jss-manager/package-lock.json
  packages/fast-jss-utilities/package-lock.json
  packages/fast-jss-utilities/package.json
  packages/fast-jss-utilities/src/colors.spec.ts
  packages/fast-jss-utilities/src/colors.ts
  packages/fast-jss-utilities/src/index.ts
  packages/fast-layouts-react/package-lock.json
  packages/fast-markdown-msft-react/package-lock.json
  packages/fast-permutator/package-lock.json
  packages/fast-sketch-library/package-lock.json
  packages/fast-tslint-rules/package-lock.json
  packages/fast-viewer-react/package-lock.json
  packages/fast-web-utilities/package-lock.json
Labels: pr : feature

#832 chore(fast-components-react-base): update an enzyme test to use mount instead of shallow
  packages/fast-animation/package-lock.json
  packages/fast-application-utilities/package-lock.json
  packages/fast-browser-extensions/package-lock.json
  packages/fast-colors/package-lock.json
  packages/fast-components-class-name-contracts-base/package-lock.json
  packages/fast-components-class-name-contracts-msft/package-lock.json
  packages/fast-components-react-base/package-lock.json
  packages/fast-components-react-base/src/horizontal-overflow/horizontal-overflow.spec.tsx
  packages/fast-components-react-msft/package-lock.json
  packages/fast-components-styles-msft/package-lock.json
  packages/fast-css-editor-react/package-lock.json
  packages/fast-development-site-react/package-lock.json
  packages/fast-form-generator-react/package-lock.json
  packages/fast-glyphs-msft/package-lock.json
  packages/fast-jest-snapshots-react/package-lock.json
  packages/fast-jss-manager-angular/package-lock.json
  packages/fast-jss-manager-react/package-lock.json
  packages/fast-jss-manager/package-lock.json
  packages/fast-jss-utilities/package-lock.json
  packages/fast-layouts-react/package-lock.json
  packages/fast-markdown-msft-react/package-lock.json
  packages/fast-sketch-library/package-lock.json
  packages/fast-tslint-rules/package-lock.json
  packages/fast-viewer-react/package-lock.json
  packages/fast-web-utilities/package-lock.json
Labels: pr : chore

#836 chore(circle-ci): update to switch to use workflows
  .circleci/config.yml
  build/clean-package-locks.js
  packages/fast-animation/package.json
Labels: pr : chore

#828 feat(subheading): add subheading component
  packages/fast-components-class-name-contracts-msft/src/index.ts
  packages/fast-components-class-name-contracts-msft/src/subheading/index.ts
  packages/fast-components-react-msft/app/examples.ts
  packages/fast-components-react-msft/src/index.ts
  packages/fast-components-react-msft/src/subheading/README.md
  packages/fast-components-react-msft/src/subheading/__snapshots__/subheading.spec.tsx.snap
  packages/fast-components-react-msft/src/subheading/examples.data.tsx
  packages/fast-components-react-msft/src/subheading/index.ts
  packages/fast-components-react-msft/src/subheading/subheading.props.ts
  packages/fast-components-react-msft/src/subheading/subheading.schema.json
  packages/fast-components-react-msft/src/subheading/subheading.spec.tsx
  packages/fast-components-react-msft/src/subheading/subheading.tsx
  packages/fast-components-styles-msft/src/index.ts
  packages/fast-components-styles-msft/src/subheading/index.ts
Labels: pr : feature
