Repository microsoft/fast, pull requests merged in 2018-03, with the labels that each got.

#105 Create travis configuration file for Travis CI
  .travis.yml
Labels: task : update, type : build, type : devops

#117 fix(package): rename fast-react-components-fluent to fast-react-components-msft
  packages/fast-react-components-msft/app/examples.ts
  packages/fast-react-components-msft/app/index.tsx
  packages/fast-react-components-msft/package-lock.json
  packages/fast-react-components-msft/package.json
  packages/fast-react-components-msft/src/button/examples.data.ts
  packages/fast-react-components-msft/src/button/index.ts
  packages/fast-react-components-msft/src/design-system/breakpoints.ts
  packages/fast-react-components-msft/src/design-system/fonts.ts
  packages/fast-react-components-msft/src/design-system/index.ts
  packages/fast-react-components-msft/src/design-system/typography.ts
  packages/fast-react-components-msft/src/examples.ts
  packages/fast-react-components-msft/src/index.ts
  packages/fast-react-components-msft/src/utilities/index.ts
  packages/fast-react-components-msft/tsconfig.json
  packages/fast-react-components-msft/webpack.config.js
Labels: reason : fixed

#130 refactor: create class-name contracts package
  package-lock.json
  packages/fast-animation/package-lock.json
  packages/fast-browser-extensions/package-lock.json
  packages/fast-components-class-name-contracts/README.md
  packages/fast-components-class-name-contracts/package-lock.json
  packages/fast-components-class-name-contracts/package.json
  packages/fast-components-class-name-contracts/src/button/index.ts
  packages/fast-components-class-name-contracts/src/index.ts
  packages/fast-components-class-name-contracts/tsconfig.json
  packages/fast-components-react-base/app/index.tsx
  packages/fast-components-react-base/package-lock.json
  packages/fast-components-react-base/package.json
  packages/fast-components-react-base/src/button/Button.tsx
  packages/fast-components-react-base/src/button/examples.data.ts
  packages/fast-components-react-msft/package-lock.json
  packages/fast-components-react-msft/src/button/index.ts
  packages/fast-development-site-react/package-lock.json
  packages/fast-jss-manager-react/package-lock.json
  packages/fast-permutator/package-lock.json
  packages/fast-viewer-react/package-lock.json
Labels: type : refactor

#128 docs(readme): adds introduction text for all packages in root readme
  README.md
  packages/fast-browser-extensions/README.md
Labels: task : update, type : docs

#131 docs: updates developer documentation
  CONTRIBUTING.md
  README.md
  packages/fast-components-class-name-contracts/README.md
Labels: task : update, type : docs

#134 docs: update root readme
  README.md
Labels: task : update, type : docs

#136 refactor: export jss-manager typings from a single repository
  packages/fast-animation/package.json
  packages/fast-components-class-name-contracts/package.json
  packages/fast-jss-manager-react/package.json
  packages/fast-jss-manager-react/src/manage-jss.tsx
  packages/fast-jss-manager/README.md
  packages/fast-jss-manager/package-lock.json
  packages/fast-jss-manager/package.json
  packages/fast-jss-manager/src/index.ts
  packages/fast-jss-manager/tsconfig.json
  packages/fast-jss-manager/tslint.json
  packages/fast-tslint-rules/package.json
Labels: task : update, type : refactor

#138 feat: add color utility package
  packages/fast-colors/README.md
  packages/fast-colors/package.json
  packages/fast-colors/src/index.ts
  packages/fast-colors/src/range.spec.ts
  packages/fast-colors/src/range.ts
  packages/fast-colors/tsconfig.json
  packages/fast-colors/tslint.json
Labels: task : create, type : feat

#140 feat(angular): add preliminary JSS manager for angular
  packages/fast-jss-manager-angular/.npmignore
  packages/fast-jss-manager-angular/README.md
  packages/fast-jss-manager-angular/build/jest-global-mocks.ts
  packages/fast-jss-manager-angular/build/setup-jest.ts
  packages/fast-jss-manager-angular/build/tslint-watch.js
  packages/fast-jss-manager-angular/package-lock.json
  packages/fast-jss-manager-angular/package.json
  packages/fast-jss-manager-angular/src/design-system.directive.ts
  packages/fast-jss-manager-angular/src/design-system.module.ts
  packages/fast-jss-manager-angular/src/index.ts
  packages/fast-jss-manager-angular/src/jss.ts
  packages/fast-jss-manager-angular/src/manage-jss.test.ts
  packages/fast-jss-manager-angular/src/manage-jss.ts
  packages/fast-jss-manager-angular/src/tsconfig.spec.json
  packages/fast-jss-manager-angular/src/utilities/get-event-names.ts
  packages/fast-jss-manager-angular/src/utilities/get-static-styles.test.ts
  packages/fast-jss-manager-angular/src/utilities/get-static-styles.ts
  packages/fast-jss-manager-angular/src/utilities/object.ts
  packages/fast-jss-manager-angular/tsconfig.json
  packages/fast-jss-manager-angular/tslint.json
  packages/fast-jss-manager-react/src/manage-jss.spec.tsx
Labels: task : update, type : feat

#146 docs: update readme
  packages/fast-jss-manager-angular/README.md
Labels: task : update, type : docs

#149 docs: update documentation for better clarity
  README.md
Labels: task : update, type : docs

#152 docs: update all references to fluent web
  .github/pull_request_template.md
  package.json
  packages/fast-animation/package.json
  packages/fast-browser-extensions/README.md
  packages/fast-browser-extensions/package.json
  packages/fast-colors/package.json
  packages/fast-components-class-name-contracts/package.json
  packages/fast-components-react-base/package.json
  packages/fast-components-react-msft/package.json
  packages/fast-development-site-react/package.json
  packages/fast-jss-manager-angular/package.json
  packages/fast-jss-manager-react/package.json
  packages/fast-jss-manager/package.json
  packages/fast-permutator/README.md
  packages/fast-permutator/__tests__/schemas/fw/action-menu.schema.json
  packages/fast-permutator/__tests__/schemas/fw/action-trigger.schema.json
  packages/fast-permutator/__tests__/schemas/fw/alert.schema.json
  packages/fast-permutator/__tests__/schemas/fw/badge.schema.json
  packages/fast-permutator/__tests__/schemas/fw/button.schema.json
  packages/fast-permutator/__tests__/schemas/fw/call-to-action.schema.json
  packages/fast-permutator/__tests__/schemas/fw/content-placement-item.schema.json
  packages/fast-permutator/__tests__/schemas/fw/context-menu.schema.json
  packages/fast-permutator/__tests__/schemas/fw/feature.schema.json
  packages/fast-permutator/__tests__/schemas/fw/file.schema.json
  packages/fast-permutator/__tests__/schemas/fw/heading-module.schema.json
  packages/fast-permutator/__tests__/schemas/fw/heading.schema.json
  packages/fast-permutator/__tests__/schemas/fw/hero-item.schema.json
  packages/fast-permutator/__tests__/schemas/fw/hyperlink.schema.json
  packages/fast-permutator/__tests__/schemas/fw/image.schema.json
  packages/fast-permutator/__tests__/schemas/fw/label.schema.json
  packages/fast-permutator/__tests__/schemas/fw/logo.schema.json
  packages/fast-permutator/__tests__/schemas/fw/mosaic-placement.schema.json
  packages/fast-permutator/__tests__/schemas/fw/mosaic.schema.json
  packages/fast-permutator/__tests__/schemas/fw/panes-placement.schema.json
  packages/fast-permutator/__tests__/schemas/fw/panes.schema.json
  packages/fast-permutator/__tests__/schemas/fw/paragraph.schema.json
  packages/fast-permutator/__tests__/schemas/fw/price.schema.json
  packages/fast-permutator/__tests__/schemas/fw/refine-item.schema.json
  packages/fast-permutator/__tests__/schemas/fw/refine-menu.schema.json
  packages/fast-permutator/__tests__/schemas/fw/subheading.schema.json
  packages/fast-permutator/__tests__/schemas/fw/supplemental-navigation.schema.json
  packages/fast-permutator/__tests__/schemas/fw/test.schema.json
  packages/fast-permutator/__tests__/schemas/fw/text-field.schema.json
  packages/fast-permutator/__tests__/schemas/fw/toggle.schema.json
  packages/fast-permutator/__tests__/test-schemas/index.js
Labels: task : update, type : docs

#155 docs: update to readme directing traffic to wiki
  README.md
Labels: task : update, type : docs

#159 add code climate configuration to project
  .codeclimate.yml
  README.md
  packages/fast-browser-extensions/src/extension/messaging/index.ts
  packages/fast-jss-manager-angular/src/manage-jss.ts
Labels: task : create, type : devops
