Repository microsoft/fast, pull requests merged in 2018-09, with the labels that each got.

#842 chore(checkbox): update to coding standards
  packages/fast-components-react-base/src/checkbox/checkbox.spec.tsx
  packages/fast-components-react-base/src/checkbox/checkbox.tsx
Labels: pr : chore

#838 chore(toggle): update to coding standards
  packages/fast-components-react-base/src/toggle/__snapshots__/toggle.spec.tsx.snap
  packages/fast-components-react-base/src/toggle/toggle.spec.tsx
  packages/fast-components-react-base/src/toggle/toggle.tsx
  packages/fast-components-react-msft/src/toggle/__snapshots__/toggle.spec.ts.snap
Labels: pr : chore

#846 chore(github): update to improve wording on feature template
  .github/ISSUE_TEMPLATE/Feature_request.md
Labels: pr : chore

#840 chore(fast-form-generator-react): update the component tracker to use the navigation utility
  packages/fast-form-generator-react/app/components/any-of/__snapshots__/any-of.spec.tsx.snap
  packages/fast-form-generator-react/app/components/any-of/any-of.schema.json
  packages/fast-form-generator-react/app/components/objects/objects.schema.json
  packages/fast-form-generator-react/src/form/form-item.children.tsx
  packages/fast-form-generator-react/src/form/form-section.props.ts
  packages/fast-form-generator-react/src/form/form.props.ts
  packages/fast-form-generator-react/src/form/form.spec.ts
  packages/fast-form-generator-react/src/form/form.tsx
  packages/fast-form-generator-react/src/form/form.utilities.ts
Labels: pr : chore

#847 chore(devops): update for devops specific files and ownership
  .github/CODEOWNERS
Labels: pr : chore

#854 fix(fast-components-react-msft): update label attribute used in color picker
  packages/fast-components-react-msft/app/color-picker.tsx
Labels: pr : fix

#860 fix(page): replaces "auto" with "0" to fix a cross-browser compatability issue regarding how "auto" is handled
  packages/fast-layouts-react/src/page/page.tsx
Labels: pr : fix

#859 fix(acrylic): sets background property to undefined instead of null to prevent error due to jss expectations
  packages/fast-jss-utilities/src/acrylic.ts
Labels: pr : fix

#869 feat(dialog): add onDismiss callback to support "soft dismiss" functionality
  packages/fast-components-react-base/src/dialog/__snapshots__/dialog.spec.tsx.snap
  packages/fast-components-react-base/src/dialog/dialog.props.ts
  packages/fast-components-react-base/src/dialog/dialog.spec.tsx
  packages/fast-components-react-base/src/dialog/dialog.tsx
  packages/fast-components-react-msft/src/dialog/__snapshots__/dialog.spec.ts.snap
Labels: pr : feature

#872 chore: use lerna independent mode
  lerna.json
  package.json
Labels: pr : chore

#876 fix(docs): update link for contributors to find good first issue
  README.md
Labels: pr : fix

#880 fix(button): add missing super of generateClassNames method when appearance prop is not set
  packages/fast-components-react-msft/src/button/button.spec.tsx
  packages/fast-components-react-msft/src/button/button.tsx
Labels: pr : fix

#887 fix(fast-components-react-msft): fix missing exports from package
  packages/fast-components-react-msft/src/caption/caption.props.ts
  packages/fast-components-react-msft/src/caption/caption.spec.tsx
  packages/fast-components-react-msft/src/caption/caption.tsx
  packages/fast-components-react-msft/src/caption/index.ts
  packages/fast-components-react-msft/src/index.ts
  packages/fast-components-react-msft/src/subheading/index.ts
Labels: pr : fix

#899 fix(caption): add missing reference for caption className contract interface
  packages/fast-components-react-msft/src/caption/index.ts
Labels: pr : fix

#911 chore(devops): remove script for cleaning up package-locks since we aren't using pac…
  build/clean-package-locks.js
Labels: pr : chore

#851 feat(call-to-action): add call to action component
  packages/fast-components-class-name-contracts-msft/src/call-to-action/index.ts
  packages/fast-components-class-name-contracts-msft/src/index.ts
  packages/fast-components-react-msft/app/examples.ts
  packages/fast-components-react-msft/src/button/__snapshots__/button.spec.tsx.snap
  packages/fast-components-react-msft/src/button/button.spec.tsx
  packages/fast-components-react-msft/src/button/button.tsx
  packages/fast-components-react-msft/src/button/examples.data.tsx
  packages/fast-components-react-msft/src/call-to-action/README.md
  packages/fast-components-react-msft/src/call-to-action/__snapshots__/call-to-action.spec.tsx.snap
  packages/fast-components-react-msft/src/call-to-action/call-to-action.props.ts
  packages/fast-components-react-msft/src/call-to-action/call-to-action.schema.json
  packages/fast-components-react-msft/src/call-to-action/call-to-action.spec.tsx
  packages/fast-components-react-msft/src/call-to-action/call-to-action.tsx
  packages/fast-components-react-msft/src/call-to-action/examples.data.tsx
  packages/fast-components-react-msft/src/call-to-action/index.ts
  packages/fast-components-react-msft/src/index.ts
  packages/fast-components-styles-msft/src/call-to-action/index.ts
  packages/fast-components-styles-msft/src/index.ts
  packages/fast-glyphs-msft/.babelrc
  packages/fast-glyphs-msft/.npmignore
  packages/fast-glyphs-msft/glyphs/arrow-right.svg
  packages/fast-glyphs-msft/package.json
Labels: pr : feature

#901 feat(style): add elevation shadow ramp and functions
  packages/fast-components-styles-msft/src/dialog/index.ts
  packages/fast-components-styles-msft/src/utilities/elevation.ts
Labels: pr : feature

#906 chore: remove unused changelog script in root package
  package.json
Labels: pr : chore

#905 chore(devops): add cross browser testing on Sauce Labs
  README.md
  build/testing/config-browsers.js
  build/testing/sauce-labs/test-browsers.js
  package.json
Labels: pr : chore

#925 fix(fast-components-react-base): update peer dependency version for `fast-web-utilities`
  packages/fast-components-react-base/package.json
Labels: pr : fix

#928 chore(docs): fix component readme for consistency
  packages/fast-components-react-base/README.md
  packages/fast-components-react-msft/README.md
Labels: pr : chore

#930 fix(call-to-action): fix glyph import due to missing package dependency
  packages/fast-components-react-msft/package.json
Labels: pr : fix

#939 chore(codeowners): add additional markdown codeowner
  .github/CODEOWNERS
Labels: pr : chore

#924 chore(devops): update build scripts with better formatting
  build/testing/config-browsers.alpha.js
  build/testing/config-browsers.beta.js
  build/testing/config-browsers.js
  build/testing/config-browsers.release.js
  build/testing/sauce-labs/test-browsers.js
  package.json
Labels: pr : chore, tag : devops

#927 docs(devops): update Sauce Labs badges and browser matrix
  README.md
Labels: pr : docs, tag : devops

#929 chore(devops): remove unneeded ts config rules
  tsconfig.json
Labels: tag : devops

#954 fix: update checkbox to render label DOM only when label text exists
  packages/fast-components-react-base/src/checkbox/__snapshots__/checkbox.spec.tsx.snap
  packages/fast-components-react-base/src/checkbox/checkbox.tsx
Labels: issue : task

#935 chore(fast-form-generator-react): update the api for react children in json schemas
  packages/fast-components-react-base/app/components/examples.data.tsx
  packages/fast-components-react-base/app/components/react-html-element.schema.json
  packages/fast-components-react-base/app/components/react-html-element.tsx
  packages/fast-components-react-base/app/index.tsx
  packages/fast-components-react-base/src/button/button.schema.json
  packages/fast-components-react-base/src/dialog/dialog.schema.json
  packages/fast-components-react-base/src/horizontal-overflow/__snapshots__/horizontal-overflow.spec.tsx.snap
  packages/fast-components-react-base/src/horizontal-overflow/examples.data.tsx
  packages/fast-components-react-base/src/horizontal-overflow/horizontal-overflow.schema.json
  packages/fast-components-react-base/src/horizontal-overflow/horizontal-overflow.spec.tsx
  packages/fast-components-react-base/src/hypertext/hypertext.schema.json
  packages/fast-components-react-base/src/label/label.schema.json
  packages/fast-components-react-base/src/progress/__snapshots__/progress.spec.tsx.snap
  packages/fast-components-react-base/src/progress/examples.data.tsx
  packages/fast-components-react-base/src/progress/progress.schema.json
  packages/fast-components-react-base/src/progress/progress.spec.tsx
  packages/fast-components-react-base/src/tabs/__snapshots__/tabs.spec.tsx.snap
  packages/fast-components-react-base/src/tabs/examples.data.tsx
  packages/fast-components-react-base/src/tabs/tab-item.schema.json
  packages/fast-components-react-base/src/tabs/tab-panel.schema.json
  packages/fast-components-react-base/src/tabs/tab.schema.json
  packages/fast-components-react-base/src/tabs/tabs.schema.json
  packages/fast-components-react-base/src/tabs/tabs.spec.tsx
  packages/fast-components-react-base/src/text-field/text-field.schema.json
  packages/fast-components-react-base/src/toggle/toggle.schema.json
  packages/fast-components-react-base/src/typography/typography.schema.json
  packages/fast-components-react-msft/src/button/button.schema.json
  packages/fast-components-react-msft/src/call-to-action/call-to-action.schema.json
  packages/fast-components-react-msft/src/caption/caption.schema.json
  packages/fast-components-react-msft/src/flipper/examples.data.tsx
  packages/fast-components-react-msft/src/flipper/flipper.schema.json
  packages/fast-components-react-msft/src/heading/heading.schema.json
  packages/fast-components-react-msft/src/metatext/metatext.schema.json
  packages/fast-components-react-msft/src/paragraph/paragraph.schema.json
  packages/fast-components-react-msft/src/subheading/subheading.schema.json
  packages/fast-development-site-react/app/app.tsx
  packages/fast-development-site-react/app/components/button/button.schema.json
  packages/fast-development-site-react/app/components/button/button.tsx
  packages/fast-development-site-react/src/components/site/index.tsx
  packages/fast-form-generator-react/README.md
  packages/fast-form-generator-react/app/components/arrays/arrays.schema.json
  packages/fast-form-generator-react/app/components/arrays/arrays.tsx
  packages/fast-form-generator-react/app/components/children/children.schema.json
  packages/fast-form-generator-react/app/components/children/children.tsx
  packages/fast-form-generator-react/app/components/general-example/general-example.schema.json
  packages/fast-form-generator-react/app/components/text-field/text-field.tsx
  packages/fast-form-generator-react/app/index.tsx
  packages/fast-form-generator-react/src/form/form-item.array.tsx
  packages/fast-form-generator-react/src/form/form-item.children.style.ts
  packages/fast-form-generator-react/src/form/form-item.children.tsx
  packages/fast-form-generator-react/src/form/form-section.tsx
  packages/fast-form-generator-react/src/form/form-section.utilities.tsx
  packages/fast-form-generator-react/src/form/form.props.ts
  packages/fast-form-generator-react/src/form/form.spec.ts
  packages/fast-form-generator-react/src/form/form.tsx
  packages/fast-form-generator-react/src/form/form.utilities.ts
  packages/fast-form-generator-react/src/form/index.ts
  packages/fast-form-generator-react/src/index.ts
  packages/fast-form-generator-react/src/utilities/form-input.style.ts
  packages/fast-form-generator-react/tsconfig.json
Labels: breaking change :boom:
