Repository microsoft/fast, pull requests merged in 2018-05, with the labels that each got.

#350 docs: update README.md
  README.md
Labels: task : update, type : docs

#353 docs: update README.md to be correct
  packages/fast-jss-utilities/README.md
Labels: task : update, type : docs

#359 fix(dev-site): add design system provider to component example factory
  packages/fast-components-react-msft/app/index.tsx
  packages/fast-development-site-react/src/utilities/componentExampleFactory.tsx
  packages/fast-development-site-react/src/utilities/componentFactory.tsx
  packages/fast-markdown-msft-react/package-lock.json
Labels: bug, reason : fixed

#361 update(packages): bumps all packages to 1.0.4
  lerna.json
  package.json
  packages/fast-animation/package.json
  packages/fast-browser-extensions/package.json
  packages/fast-colors/package.json
  packages/fast-components-class-name-contracts-base/package.json
  packages/fast-components-class-name-contracts-msft/package.json
  packages/fast-components-react-base/package.json
  packages/fast-components-react-msft/package.json
  packages/fast-components-styles-msft/package.json
  packages/fast-development-site-react/package.json
  packages/fast-form-generator-react/package.json
  packages/fast-glyphs-msft/package.json
  packages/fast-jest-snapshots-react/package.json
  packages/fast-jss-manager-angular/package.json
  packages/fast-jss-manager-react/package.json
  packages/fast-jss-manager/package.json
  packages/fast-jss-utilities/package.json
  packages/fast-markdown-msft-react/package.json
  packages/fast-permutator/package.json
  packages/fast-tslint-rules/package.json
  packages/fast-viewer-react/package.json
Labels: task : update

#365 build(travis-ci) : fix build timeout issues
  .travis.yml
  packages/fast-animation/package.json
  packages/fast-components-react-base/package.json
  packages/fast-components-react-msft/package.json
  packages/fast-development-site-react/package.json
  packages/fast-form-generator-react/package.json
  packages/fast-permutator/package.json
  packages/fast-viewer-react/package.json
Labels: pr : fix, tag : devops

#363 feat(form generator): adds styling scaffolding and JSS for select
  packages/fast-form-generator-react/app/components/number-field/__snapshots__/number-field.spec.tsx.snap
  packages/fast-form-generator-react/app/components/text-field/__snapshots__/text-field.spec.tsx.snap
  packages/fast-form-generator-react/app/components/weight-properties/__snapshots__/weight-properties.spec.tsx.snap
  packages/fast-form-generator-react/package.json
  packages/fast-form-generator-react/src/class-name-contracts/form-item.select.class-name-contract.ts
  packages/fast-form-generator-react/src/class-name-contracts/index.ts
  packages/fast-form-generator-react/src/form/form-item.select.style.ts
  packages/fast-form-generator-react/src/form/form-item.select.tsx
Labels: pr : feature

#362 feat(form): add the form generator to the development site
  package-lock.json
  packages/fast-development-site-react/app/app.tsx
  packages/fast-development-site-react/app/components/button.schema.json
  packages/fast-development-site-react/app/components/button.tsx
  packages/fast-development-site-react/app/components/paragraph.schema.json
  packages/fast-development-site-react/app/components/paragraph.tsx
  packages/fast-development-site-react/package-lock.json
  packages/fast-development-site-react/package.json
  packages/fast-development-site-react/src/components/shell/pane.tsx
  packages/fast-development-site-react/src/components/site/action-bar.tsx
  packages/fast-development-site-react/src/components/site/category-item.tsx
  packages/fast-development-site-react/src/components/site/category.tsx
  packages/fast-development-site-react/src/components/site/component-view-toggle.tsx
  packages/fast-development-site-react/src/components/site/component-wrapper.tsx
  packages/fast-development-site-react/src/components/site/index.tsx
  packages/fast-development-site-react/src/components/toc/toc-item.tsx
  packages/fast-development-site-react/src/utilities/componentExampleFactory.tsx
  packages/fast-development-site-react/src/utilities/componentFactory.tsx
  packages/fast-development-site-react/typings.d.ts
  packages/fast-form-generator-react/app/index.tsx
  packages/fast-form-generator-react/package.json
  packages/fast-form-generator-react/src/form/form-item.select.tsx
  packages/fast-markdown-msft-react/package.json
Labels: pr : feature

#377 fix(button): fixes button import which caused it to be unusable outside the monorepository
  packages/fast-components-react-msft/src/button/button.tsx
Labels: pr : fix

#373 chore(packages): update to publish packages
  .travis.yml
Labels: pr : chore

#381 chore(packages): add ignore and spacing formatting
  .gitignore
  .travis.yml
Labels: pr : chore

#384 chore(packages): add configurations to fix Travis CI errors during Lerna publish
  .travis.yml
Labels: pr : chore

#385 chore(packages): add condition to ignore code coverage for deploy
  .travis.yml
Labels: pr : chore

#372 fix readme.md to use correct profile link and text values.
  packages/fast-colors/README.md
Labels: pr : docs

#383 feat(docs): add development site tools panel
  packages/fast-development-site-react/app/app.tsx
  packages/fast-development-site-react/src/components/shell/action-bar.tsx
  packages/fast-development-site-react/src/components/shell/canvas.tsx
  packages/fast-development-site-react/src/components/shell/pane.tsx
  packages/fast-development-site-react/src/components/site/action-bar.tsx
  packages/fast-development-site-react/src/components/site/component-view.tsx
  packages/fast-development-site-react/src/components/site/component-wrapper.tsx
  packages/fast-development-site-react/src/components/site/dev-tools.tsx
  packages/fast-development-site-react/src/components/site/index.tsx
  packages/fast-development-site-react/src/components/toc/toc-menu.tsx
Labels: pr : feature

#388 chore(packages): update to ignore test coverage for publishing
  .travis.yml
  lerna.json
Labels: pr : chore

#389 chore(packages): updates to include debugging
  .travis.yml
Labels: pr : chore

#390 update to use script in deploy not npm
  .travis.yml
Labels: pr : chore

#391 chore(packages): update to include token and email in .npmrc file
  .travis.yml
Labels: pr : chore

#393 chore(packages): update to configuration with lerna publish
  .travis.yml
Labels: pr : chore

#394 chore(packages): add conventional commits and status to publish
  .travis.yml
Labels: pr : chore

#392 feat(form generator): adds JSS
  packages/fast-form-generator-react/app/components/align-horizontal/__snapshots__/align-horizontal.spec.tsx.snap
  packages/fast-form-generator-react/app/components/align-horizontal/align-horizontal.schema.json
  packages/fast-form-generator-react/app/components/align-vertical/__snapshots__/align-vertical.spec.tsx.snap
  packages/fast-form-generator-react/app/components/align-vertical/align-vertical.schema.json
  packages/fast-form-generator-react/app/components/any-of/__snapshots__/any-of.spec.tsx.snap
  packages/fast-form-generator-react/app/components/any-of/any-of.schema.json
  packages/fast-form-generator-react/app/components/arrays/arrays.schema.json
  packages/fast-form-generator-react/app/components/attribute-assignment/__snapshots__/attribute-assignment.spec.tsx.snap
  packages/fast-form-generator-react/app/components/checkbox/__snapshots__/checkbox.spec.tsx.snap
  packages/fast-form-generator-react/app/components/checkbox/checkbox.schema.json
  packages/fast-form-generator-react/app/components/number-field/__snapshots__/number-field.spec.tsx.snap
  packages/fast-form-generator-react/app/components/number-field/number-field.schema.json
  packages/fast-form-generator-react/app/components/objects/__snapshots__/objects.spec.tsx.snap
  packages/fast-form-generator-react/app/components/one-of/__snapshots__/one-of.spec.tsx.snap
  packages/fast-form-generator-react/app/components/text-field/__snapshots__/text-field.spec.tsx.snap
  packages/fast-form-generator-react/app/components/text-field/text-field.schema.json
  packages/fast-form-generator-react/app/components/theme/__snapshots__/theme.spec.tsx.snap
  packages/fast-form-generator-react/app/components/theme/theme.schema.json
  packages/fast-form-generator-react/app/components/weight-properties/__snapshots__/weight-properties.spec.tsx.snap
  packages/fast-form-generator-react/app/components/weight-properties/weight-properties.schema.json
  packages/fast-form-generator-react/app/index.tsx
  packages/fast-form-generator-react/src/class-name-contracts/form-item.align-horizontal.class-name-contract.ts
  packages/fast-form-generator-react/src/class-name-contracts/form-item.align-vertical.class-name-contract.ts
  packages/fast-form-generator-react/src/class-name-contracts/form-item.array.class-name-contract.ts
  packages/fast-form-generator-react/src/class-name-contracts/form-item.checkbox.class-name-contract.ts
  packages/fast-form-generator-react/src/class-name-contracts/form-item.children.class-name-contract.ts
  packages/fast-form-generator-react/src/class-name-contracts/form-item.number-field.class-name-contract.ts
  packages/fast-form-generator-react/src/class-name-contracts/form-item.select.class-name-contract.ts
  packages/fast-form-generator-react/src/class-name-contracts/form-item.textarea.class-name-contract.ts
  packages/fast-form-generator-react/src/class-name-contracts/form-item.theme.class-name-contract.ts
  packages/fast-form-generator-react/src/class-name-contracts/form-section.class-name-contract.ts
  packages/fast-form-generator-react/src/class-name-contracts/form.class-name-contract.ts
  packages/fast-form-generator-react/src/class-name-contracts/index.ts
  packages/fast-form-generator-react/src/form/form-item.align-horizontal.style.ts
  packages/fast-form-generator-react/src/form/form-item.align-horizontal.tsx
  packages/fast-form-generator-react/src/form/form-item.align-vertical.style.ts
  packages/fast-form-generator-react/src/form/form-item.align-vertical.tsx
  packages/fast-form-generator-react/src/form/form-item.array.style.ts
  packages/fast-form-generator-react/src/form/form-item.array.tsx
  packages/fast-form-generator-react/src/form/form-item.checkbox.style.ts
  packages/fast-form-generator-react/src/form/form-item.checkbox.tsx
  packages/fast-form-generator-react/src/form/form-item.children.style.ts
  packages/fast-form-generator-react/src/form/form-item.children.tsx
  packages/fast-form-generator-react/src/form/form-item.number-field.style.ts
  packages/fast-form-generator-react/src/form/form-item.number-field.tsx
  packages/fast-form-generator-react/src/form/form-item.select.style.ts
  packages/fast-form-generator-react/src/form/form-item.select.tsx
  packages/fast-form-generator-react/src/form/form-item.textarea.style.ts
  packages/fast-form-generator-react/src/form/form-item.textarea.tsx
  packages/fast-form-generator-react/src/form/form-item.theme.style.ts
  packages/fast-form-generator-react/src/form/form-item.theme.tsx
  packages/fast-form-generator-react/src/form/form-section.style.ts
  packages/fast-form-generator-react/src/form/form-section.tsx
  packages/fast-form-generator-react/src/form/form.style.ts
  packages/fast-form-generator-react/src/form/form.tsx
  packages/fast-form-generator-react/src/form/sorting.tsx
  packages/fast-form-generator-react/src/utilities/form-input.style.ts
Labels: pr : feature

#387 docs(readme): update hyperlinks for label changes
  README.md
Labels: pr : docs

#400 chore(release): update packages to v1.1.0
  CHANGELOG.md
  lerna.json
  packages/fast-animation/CHANGELOG.md
  packages/fast-animation/package.json
  packages/fast-browser-extensions/CHANGELOG.md
  packages/fast-browser-extensions/package.json
  packages/fast-colors/CHANGELOG.md
  packages/fast-colors/package.json
  packages/fast-components-class-name-contracts-base/CHANGELOG.md
  packages/fast-components-class-name-contracts-base/package.json
  packages/fast-components-class-name-contracts-msft/CHANGELOG.md
  packages/fast-components-class-name-contracts-msft/package.json
  packages/fast-components-react-base/CHANGELOG.md
  packages/fast-components-react-base/package.json
  packages/fast-components-react-msft/CHANGELOG.md
  packages/fast-components-react-msft/package.json
  packages/fast-components-styles-msft/CHANGELOG.md
  packages/fast-components-styles-msft/package.json
  packages/fast-development-site-react/CHANGELOG.md
  packages/fast-development-site-react/package.json
  packages/fast-form-generator-react/CHANGELOG.md
  packages/fast-form-generator-react/package.json
  packages/fast-glyphs-msft/CHANGELOG.md
  packages/fast-glyphs-msft/package.json
  packages/fast-jest-snapshots-react/CHANGELOG.md
  packages/fast-jest-snapshots-react/package.json
  packages/fast-jss-manager-angular/CHANGELOG.md
  packages/fast-jss-manager-angular/package.json
  packages/fast-jss-manager-react/CHANGELOG.md
  packages/fast-jss-manager-react/package.json
  packages/fast-jss-manager/CHANGELOG.md
  packages/fast-jss-manager/package.json
  packages/fast-jss-utilities/CHANGELOG.md
  packages/fast-jss-utilities/package.json
  packages/fast-markdown-msft-react/CHANGELOG.md
  packages/fast-markdown-msft-react/package.json
  packages/fast-permutator/CHANGELOG.md
  packages/fast-permutator/package.json
  packages/fast-tslint-rules/CHANGELOG.md
  packages/fast-tslint-rules/package.json
  packages/fast-viewer-react/CHANGELOG.md
  packages/fast-viewer-react/package.json
Labels: pr : chore

#371 feat(checkbox): update styling and incorrect states
  packages/fast-components-class-name-contracts-base/src/checkbox/index.ts
  packages/fast-components-react-base/src/checkbox/__snapshots__/checkbox.spec.ts.snap
  packages/fast-components-react-base/src/checkbox/checkbox.props.ts
  packages/fast-components-react-base/src/checkbox/checkbox.tsx
  packages/fast-components-react-base/src/checkbox/examples.data.ts
  packages/fast-components-react-msft/src/checkbox/examples.data.ts
  packages/fast-components-styles-msft/src/checkbox/index.ts
Labels: pr : feature

#403 test(snapshots): add missing snapshots for non-Chroma JSS components
  packages/fast-components-react-msft/src/divider/__snapshots__/divider.spec.ts.snap
  packages/fast-components-react-msft/src/divider/divider.spec.ts
  packages/fast-components-react-msft/src/hypertext/__snapshots__/hypertext.spec.ts.snap
  packages/fast-components-react-msft/src/hypertext/hypertext.spec.ts
  packages/fast-components-react-msft/src/image/__snapshots__/image.spec.ts.snap
  packages/fast-components-react-msft/src/image/image.spec.ts
  packages/fast-components-react-msft/src/label/__snapshots__/label.spec.ts.snap
  packages/fast-components-react-msft/src/label/label.spec.ts
  packages/fast-components-react-msft/src/typography/__snapshots__/typography.spec.ts.snap
  packages/fast-components-react-msft/src/typography/typography.spec.ts
Labels: pr : chore

#405 fix(typography): fixes an issue where typography was not being exported
  packages/fast-components-react-msft/src/index.ts
Labels: pr : fix

#411 fix(button): fixes an issue where href was not being passed as part of the created anchor element
  packages/fast-components-react-base/src/button/__snapshots__/button.spec.ts.snap
  packages/fast-components-react-base/src/button/button.tsx
Labels: pr : fix

#409 fix(jss): fix errors caused by un-linked JSS rules
  packages/fast-components-styles-msft/src/button/index.ts
  packages/fast-components-styles-msft/src/toggle/index.ts
  packages/fast-development-site-react/src/components/site/action-bar.tsx
  packages/fast-development-site-react/src/components/site/component-view-toggle.tsx
Labels: pr : fix

#399 feat(code-preview): add react code preview
  packages/fast-development-site-react/app/app.tsx
  packages/fast-development-site-react/app/components/button.schema.json
  packages/fast-development-site-react/app/components/button.tsx
  packages/fast-development-site-react/src/components/site/action-bar.tsx
  packages/fast-development-site-react/src/components/site/dev-tools-code-preview.tsx
  packages/fast-development-site-react/src/components/site/dev-tools.tsx
  packages/fast-development-site-react/src/components/site/index.tsx
Labels: pr : feature

#416 fix(development-site): update styling
  packages/fast-components-react-msft/src/image/__snapshots__/image.spec.ts.snap
  packages/fast-components-react-msft/src/image/examples.data.ts
  packages/fast-development-site-react/src/components/shell/action-bar.tsx
  packages/fast-development-site-react/src/components/shell/index.tsx
  packages/fast-development-site-react/src/components/shell/pane.tsx
  packages/fast-development-site-react/src/components/shell/row.tsx
  packages/fast-development-site-react/src/components/site/action-bar.tsx
  packages/fast-development-site-react/src/components/site/component-view.tsx
  packages/fast-development-site-react/src/components/site/component-wrapper.tsx
  packages/fast-development-site-react/src/components/site/index.tsx
Labels: pr : fix

#418 feat(form generator): add SVGs, additional JSS, and general examples
  packages/fast-form-generator-react/app/components/align-horizontal/align-horizontal.tsx
  packages/fast-form-generator-react/app/components/align-vertical/__snapshots__/align-vertical.spec.tsx.snap
  packages/fast-form-generator-react/app/components/align-vertical/align-vertical.tsx
  packages/fast-form-generator-react/app/components/checkbox/__snapshots__/checkbox.spec.tsx.snap
  packages/fast-form-generator-react/app/components/general-example/__snapshots__/general-example.spec.tsx.snap
  packages/fast-form-generator-react/app/components/general-example/general-example.config.ts
  packages/fast-form-generator-react/app/components/general-example/general-example.schema.json
  packages/fast-form-generator-react/app/components/general-example/general-example.spec.tsx
  packages/fast-form-generator-react/app/components/general-example/general-example.tsx
  packages/fast-form-generator-react/app/components/index.ts
  packages/fast-form-generator-react/app/components/number-field/number-field.tsx
  packages/fast-form-generator-react/app/components/text-field/text-field.tsx
  packages/fast-form-generator-react/app/components/theme/theme.tsx
  packages/fast-form-generator-react/app/components/weight-properties/weight-properties.tsx
  packages/fast-form-generator-react/app/index.tsx
  packages/fast-form-generator-react/src/class-name-contracts/form-item.array.class-name-contract.ts
  packages/fast-form-generator-react/src/class-name-contracts/form-item.children.class-name-contract.ts
  packages/fast-form-generator-react/src/form/form-item.align-vertical.tsx
  packages/fast-form-generator-react/src/form/form-item.array.style.ts
  packages/fast-form-generator-react/src/form/form-item.array.tsx
  packages/fast-form-generator-react/src/form/form-item.checkbox.style.ts
  packages/fast-form-generator-react/src/form/form-item.checkbox.tsx
  packages/fast-form-generator-react/src/form/form-item.children.style.ts
  packages/fast-form-generator-react/src/form/form-item.children.tsx
  packages/fast-form-generator-react/src/form/form-item.number-field.style.ts
  packages/fast-form-generator-react/src/form/form.style.ts
  packages/fast-form-generator-react/src/utilities/form-input.style.ts
Labels: pr : feature

#420 feat(form generator): updates styles found in configuration pane
  packages/fast-animation/package-lock.json
  packages/fast-browser-extensions/package-lock.json
  packages/fast-colors/package-lock.json
  packages/fast-components-class-name-contracts-base/package-lock.json
  packages/fast-components-class-name-contracts-msft/package-lock.json
  packages/fast-components-react-base/package-lock.json
  packages/fast-components-react-msft/package-lock.json
  packages/fast-components-styles-msft/package-lock.json
  packages/fast-development-site-react/app/components/button.schema.json
  packages/fast-development-site-react/app/components/paragraph.schema.json
  packages/fast-development-site-react/package-lock.json
  packages/fast-development-site-react/src/components/shell/pane.tsx
  packages/fast-form-generator-react/package-lock.json
  packages/fast-form-generator-react/src/form/form-item.children.style.ts
  packages/fast-form-generator-react/src/form/form-item.textarea.style.ts
  packages/fast-form-generator-react/src/form/form-item.theme.style.ts
  packages/fast-form-generator-react/src/form/form-section.style.ts
  packages/fast-form-generator-react/src/form/form.style.ts
  packages/fast-form-generator-react/src/utilities/form-input.style.ts
  packages/fast-glyphs-msft/package-lock.json
  packages/fast-jest-snapshots-react/package-lock.json
  packages/fast-jss-manager-angular/package-lock.json
  packages/fast-jss-manager-react/package-lock.json
  packages/fast-jss-manager/package-lock.json
  packages/fast-jss-utilities/package-lock.json
  packages/fast-markdown-msft-react/package-lock.json
  packages/fast-permutator/package-lock.json
  packages/fast-tslint-rules/package-lock.json
  packages/fast-viewer-react/package-lock.json
Labels: pr : feature

#413 chore(schemas): add schemas for components to packages which use the development site package
  build/copy-schemas.js
  package.json
  packages/fast-components-react-base/app/index.tsx
  packages/fast-components-react-base/package.json
  packages/fast-components-react-base/src/button/button.schema.json
  packages/fast-components-react-base/src/button/examples.data.ts
  packages/fast-components-react-base/src/checkbox/checkbox.schema.json
  packages/fast-components-react-base/src/checkbox/examples.data.ts
  packages/fast-components-react-base/src/divider/divider.schema.json
  packages/fast-components-react-base/src/divider/examples.data.ts
  packages/fast-components-react-base/src/hypertext/examples.data.ts
  packages/fast-components-react-base/src/hypertext/hypertext.schema.json
  packages/fast-components-react-base/src/image/examples.data.ts
  packages/fast-components-react-base/src/image/image.schema.json
  packages/fast-components-react-base/src/label/examples.data.ts
  packages/fast-components-react-base/src/label/label.schema.json
  packages/fast-components-react-base/src/toggle/examples.data.ts
  packages/fast-components-react-base/src/toggle/toggle.schema.json
  packages/fast-components-react-base/src/typography/examples.data.ts
  packages/fast-components-react-base/src/typography/typography.schema.json
  packages/fast-components-react-base/tsconfig.json
  packages/fast-components-react-msft/app/index.tsx
  packages/fast-components-react-msft/package.json
  packages/fast-components-react-msft/src/button/button.schema.json
  packages/fast-components-react-msft/src/button/examples.data.ts
  packages/fast-components-react-msft/src/checkbox/examples.data.ts
  packages/fast-components-react-msft/src/divider/examples.data.ts
  packages/fast-components-react-msft/src/heading/examples.data.ts
  packages/fast-components-react-msft/src/heading/heading.schema.json
  packages/fast-components-react-msft/src/hypertext/examples.data.ts
  packages/fast-components-react-msft/src/image/examples.data.ts
  packages/fast-components-react-msft/src/label/examples.data.ts
  packages/fast-components-react-msft/src/toggle/examples.data.ts
  packages/fast-components-react-msft/src/typography/examples.data.ts
  packages/fast-components-react-msft/tsconfig.json
  packages/fast-development-site-react/package.json
  packages/fast-development-site-react/src/components/site/dev-tools-code-preview.tsx
  packages/fast-development-site-react/src/components/site/index.tsx
  packages/fast-development-site-react/src/utilities/component-example-factory.tsx
  packages/fast-development-site-react/src/utilities/component-factory.tsx
  packages/fast-development-site-react/src/utilities/form-child-from-examples-factory.ts
  packages/fast-development-site-react/src/utilities/index.ts
  packages/fast-jest-snapshots-react/src/index.ts
Labels: pr : chore

#424 chore(dev-site): fix dev site spacing and styling issues for the left pane and header
  packages/fast-development-site-react/src/components/shell/header.tsx
  packages/fast-development-site-react/src/components/shell/pane.tsx
  packages/fast-development-site-react/src/components/site/index.tsx
  packages/fast-development-site-react/src/components/toc/toc-menu.tsx
  packages/fast-form-generator-react/app/components/align-horizontal/__snapshots__/align-horizontal.spec.tsx.snap
  packages/fast-form-generator-react/app/components/align-vertical/__snapshots__/align-vertical.spec.tsx.snap
  packages/fast-form-generator-react/app/components/any-of/__snapshots__/any-of.spec.tsx.snap
  packages/fast-form-generator-react/app/components/attribute-assignment/__snapshots__/attribute-assignment.spec.tsx.snap
  packages/fast-form-generator-react/app/components/checkbox/__snapshots__/checkbox.spec.tsx.snap
  packages/fast-form-generator-react/app/components/general-example/__snapshots__/general-example.spec.tsx.snap
  packages/fast-form-generator-react/app/components/number-field/__snapshots__/number-field.spec.tsx.snap
  packages/fast-form-generator-react/app/components/objects/__snapshots__/objects.spec.tsx.snap
  packages/fast-form-generator-react/app/components/one-of/__snapshots__/one-of.spec.tsx.snap
  packages/fast-form-generator-react/app/components/text-field/__snapshots__/text-field.spec.tsx.snap
  packages/fast-form-generator-react/app/components/theme/__snapshots__/theme.spec.tsx.snap
  packages/fast-form-generator-react/app/components/weight-properties/__snapshots__/weight-properties.spec.tsx.snap
  packages/fast-form-generator-react/src/form/form.props.ts
  packages/fast-form-generator-react/src/form/form.tsx
Labels: pr : chore

#426 fix(form generator): fixes drag and drop, updates styles and shape
  packages/fast-form-generator-react/package-lock.json
  packages/fast-form-generator-react/src/class-name-contracts/form-item.array.class-name-contract.ts
  packages/fast-form-generator-react/src/class-name-contracts/form-item.children.class-name-contract.ts
  packages/fast-form-generator-react/src/form/form-item.array.style.ts
  packages/fast-form-generator-react/src/form/form-item.array.tsx
  packages/fast-form-generator-react/src/form/form-item.children.style.ts
  packages/fast-form-generator-react/src/form/sorting.tsx
  packages/fast-form-generator-react/src/utilities/form-input.style.ts
Labels: pr : fix

#423 chore: hide empty tab panels and detail section
  packages/fast-development-site-react/src/components/site/action-bar.tsx
  packages/fast-development-site-react/src/components/site/component-view.tsx
  packages/fast-development-site-react/src/components/site/component-wrapper.tsx
  packages/fast-development-site-react/src/components/site/dev-tools.tsx
Labels: pr : chore

#434 fix(svg): fix some malformed SVG icons
  packages/fast-form-generator-react/src/form/form-item.array.style.ts
  packages/fast-form-generator-react/src/form/form-item.children.style.ts
  packages/fast-form-generator-react/src/form/form-section.style.ts
  packages/fast-form-generator-react/src/utilities/form-input.style.ts
Labels: pr : fix

#401 chore(circle-ci): add initial configuration
  .circleci/config.yml
  .circleci/run-build-locally.sh
  .circleci/run-coverage-locally.sh
  .travis.yml
  README.md
Labels: pr : chore

#438 feat(dev-site): adds error boundary to dev site component wrapper to prevent entire views from breaking
  packages/fast-development-site-react/src/components/site/component-wrapper.tsx
  packages/fast-development-site-react/src/utilities/error-boundary.tsx
  packages/fast-development-site-react/src/utilities/index.ts
Labels: pr : feature

#443 chore: update code coverage for circle-ci
  .circleci/config.yml
  .circleci/run-coverage-locally.sh
  packages/fast-jss-manager-react/package.json
  packages/fast-markdown-msft-react/package.json
Labels: pr : chore

#437 fix(form generator): fix malformed vertical alignment svgs and update const for readability
  packages/fast-form-generator-react/src/form/form-item.align-horizontal.style.ts
  packages/fast-form-generator-react/src/form/form-item.align-vertical.style.ts
Labels: pr : fix

#444 update to use env variables on circle ci web
  .circleci/config.yml
  .circleci/run-coverage-locally.sh
Labels: pr : chore

#440 fix(development site): add font-family globally
  packages/fast-development-site-react/src/components/shell/index.tsx
  packages/fast-development-site-react/src/components/site/index.tsx
Labels: pr : fix

#445 chore: remove environment vars for circle-ci
  .circleci/config.yml
Labels: pr : chore

#448 feat(schema): add schema view to dev tools
  packages/fast-development-site-react/src/components/site/dev-tools.tsx
  packages/fast-development-site-react/src/components/site/index.tsx
Labels: pr : feature

#450 update readme to remove travis ci
  README.md
Labels: pr : docs

#449 feat(form generator): add focus/hover states
  packages/fast-form-generator-react/src/form/form-item.array.style.ts
  packages/fast-form-generator-react/src/form/form-item.array.tsx
  packages/fast-form-generator-react/src/form/form-item.checkbox.style.ts
  packages/fast-form-generator-react/src/form/form-item.children.style.ts
  packages/fast-form-generator-react/src/form/form-item.children.tsx
  packages/fast-form-generator-react/src/form/form-item.theme.style.ts
  packages/fast-form-generator-react/src/form/form-section.style.ts
  packages/fast-form-generator-react/src/utilities/form-input.style.ts
Labels: pr : feature

#451 docs: update repository home page
  README.md
Labels: pr : docs

#463 fix(dev-site): fixes html5 validation issues with dev site markup
  packages/fast-development-site-react/src/components/site/index.tsx
  packages/fast-development-site-react/src/components/toc/toc-item.tsx
Labels: pr : fix

#458 docs: update animation readme
  packages/fast-animation/README.md
Labels: pr : docs

#461 feat(shell): add shell package with app-grid
  packages/fast-development-site-react/package.json
  packages/fast-development-site-react/src/components/shell/action-bar.tsx
  packages/fast-development-site-react/src/components/shell/canvas.tsx
  packages/fast-development-site-react/src/components/shell/header.tsx
  packages/fast-development-site-react/src/components/shell/index.tsx
  packages/fast-development-site-react/src/components/shell/pane.tsx
  packages/fast-development-site-react/src/components/shell/row.tsx
  packages/fast-development-site-react/src/components/site/action-bar.tsx
  packages/fast-development-site-react/src/components/site/index.tsx
  packages/fast-layouts-react/.babelrc
  packages/fast-layouts-react/app/index.tsx
  packages/fast-layouts-react/package-lock.json
  packages/fast-layouts-react/package.json
  packages/fast-layouts-react/src/canvas/canvas.props.ts
  packages/fast-layouts-react/src/canvas/canvas.tsx
  packages/fast-layouts-react/src/canvas/index.ts
  packages/fast-layouts-react/src/container/container.props.ts
  packages/fast-layouts-react/src/container/container.tsx
  packages/fast-layouts-react/src/container/index.ts
  packages/fast-layouts-react/src/foundation/foundation.props.ts
  packages/fast-layouts-react/src/foundation/foundation.test.ts
  packages/fast-layouts-react/src/foundation/foundation.ts
  packages/fast-layouts-react/src/foundation/index.ts
  packages/fast-layouts-react/src/index.ts
  packages/fast-layouts-react/src/pane/index.ts
  packages/fast-layouts-react/src/pane/pane.props.ts
  packages/fast-layouts-react/src/pane/pane.tsx
  packages/fast-layouts-react/src/row/index.ts
  packages/fast-layouts-react/src/row/row.props.ts
  packages/fast-layouts-react/src/row/row.tsx
  packages/fast-layouts-react/src/utilities/index.ts
  packages/fast-layouts-react/tsconfig.json
  packages/fast-layouts-react/tslint.json
  packages/fast-layouts-react/webpack.config.js
Labels: pr : feature

#467 feat(layouts): create configurable breakpoint tracker utility
  packages/fast-layouts-react/package-lock.json
  packages/fast-layouts-react/src/utilities/breakpoint-tracker.spec.ts
  packages/fast-layouts-react/src/utilities/breakpoint-tracker.ts
  packages/fast-layouts-react/src/utilities/index.ts
  packages/fast-layouts-react/src/utilities/string-extensions.ts
  packages/fast-layouts-react/tsconfig.json
Labels: pr : feature

#471 feat(layouts): add page, grid, and column layout configuration
  packages/fast-layouts-react/app/index.tsx
  packages/fast-layouts-react/src/column/column.props.ts
  packages/fast-layouts-react/src/column/column.tsx
  packages/fast-layouts-react/src/column/index.ts
  packages/fast-layouts-react/src/grid/grid.props.ts
  packages/fast-layouts-react/src/grid/grid.tsx
  packages/fast-layouts-react/src/grid/index.ts
  packages/fast-layouts-react/src/page/index.ts
  packages/fast-layouts-react/src/page/page.props.ts
  packages/fast-layouts-react/src/page/page.tsx
  packages/fast-layouts-react/src/utilities/breakpoint-tracker.spec.ts
  packages/fast-layouts-react/src/utilities/breakpoint-tracker.ts
  packages/fast-layouts-react/src/utilities/breakpoints.ts
Labels: pr : feature

#476 chore(perf): remove unnecessary instances of lodash in favor of lodash-es and add bundle analyzer to react-msft for debugging perf
  packages/fast-animation/client/examples/app/app.tsx
  packages/fast-animation/package-lock.json
  packages/fast-animation/package.json
  packages/fast-components-react-base/package-lock.json
  packages/fast-components-react-base/package.json
  packages/fast-components-react-base/webpack.config.js
  packages/fast-components-react-msft/package-lock.json
  packages/fast-components-react-msft/package.json
  packages/fast-components-react-msft/webpack.config.js
  packages/fast-layouts-react/src/pane/pane.tsx
Labels: pr : chore

#478 chore(perf): reduces production bundle size by enabling webpack tree shaking and removing duplicated dependencies
  packages/fast-colors/package.json
  packages/fast-components-class-name-contracts-base/package.json
  packages/fast-components-class-name-contracts-msft/package.json
  packages/fast-components-react-base/package.json
  packages/fast-components-react-msft/package.json
  packages/fast-components-react-msft/webpack.config.js
  packages/fast-components-styles-msft/package.json
  packages/fast-development-site-react/package.json
  packages/fast-form-generator-react/package.json
  packages/fast-glyphs-msft/package.json
  packages/fast-jest-snapshots-react/package.json
  packages/fast-jss-manager-angular/package.json
  packages/fast-jss-manager-react/package.json
  packages/fast-jss-manager/package.json
  packages/fast-jss-utilities/package.json
  packages/fast-layouts-react/package.json
  packages/fast-markdown-msft-react/package.json
  packages/fast-permutator/__tests__/test-utils/index.js
  packages/fast-permutator/package.json
  packages/fast-permutator/src/utilities/get-deep-prop-locations.js
  packages/fast-permutator/src/utilities/get-example.js
  packages/fast-permutator/src/utilities/permutate-schemas.js
  packages/fast-permutator/src/utilities/remove-empty-objects.js
  packages/fast-permutator/src/utilities/remove-undefined.js
  packages/fast-permutator/src/utilities/resolve-all-of.js
  packages/fast-permutator/src/utilities/resolve-dependencies.js
  packages/fast-permutator/src/utilities/resolve-not-required.js
  packages/fast-permutator/src/utilities/resolve-one-of-any-of.js
  packages/fast-permutator/src/utilities/resolve-recursive-references.js
  packages/fast-permutator/src/utilities/resolve-references.js
  packages/fast-permutator/src/utilities/resolve-schema-props.js
  packages/fast-permutator/src/utilities/set-deep-object.js
  packages/fast-tslint-rules/package.json
  packages/fast-viewer-react/package.json
Labels: pr : chore

#398 feat(textfield) : add new component
  packages/fast-components-class-name-contracts-base/src/index.ts
  packages/fast-components-class-name-contracts-base/src/text-field/index.ts
  packages/fast-components-react-base/app/examples.ts
  packages/fast-components-react-base/src/index.ts
  packages/fast-components-react-base/src/text-field/README.md
  packages/fast-components-react-base/src/text-field/__snapshots__/text-field.spec.ts.snap
  packages/fast-components-react-base/src/text-field/examples.data.tsx
  packages/fast-components-react-base/src/text-field/index.ts
  packages/fast-components-react-base/src/text-field/text-field.props.ts
  packages/fast-components-react-base/src/text-field/text-field.schema.json
  packages/fast-components-react-base/src/text-field/text-field.spec.ts
  packages/fast-components-react-base/src/text-field/text-field.tsx
  packages/fast-components-react-msft/app/examples.ts
  packages/fast-components-react-msft/src/index.ts
  packages/fast-components-react-msft/src/text-field/examples.data.ts
  packages/fast-components-react-msft/src/text-field/index.ts
  packages/fast-components-styles-msft/src/index.ts
  packages/fast-components-styles-msft/src/text-field/index.ts
Labels: pr : feature

#488 chore(style): fit and finish for components and doc site
  packages/fast-components-styles-msft/src/button/index.ts
  packages/fast-components-styles-msft/src/checkbox/index.ts
  packages/fast-components-styles-msft/src/label/index.ts
  packages/fast-components-styles-msft/src/toggle/index.ts
  packages/fast-development-site-react/src/components/shell/header.tsx
  packages/fast-development-site-react/src/components/site/action-bar.tsx
  packages/fast-development-site-react/src/components/toc/toc-menu.tsx
Labels: pr : chore

#489 fix(checkbox): fix broken indeterminate state UI in Firefox
  packages/fast-components-styles-msft/src/checkbox/index.ts
Labels: pr : fix

#484 add Discord link to join the community
  README.md
Labels: pr : docs

#492 chore(animation): fixes incorrect npm registry config and unmarks package as private
  packages/fast-animation/.npmignore
  packages/fast-animation/package.json
Labels: pr : chore
