Repository microsoft/fast, pull requests merged in 2018-06, with the labels that each got.

#490 docs: update to contribution policy
  CONTRIBUTING.md
Labels: pr : docs

#495 feat: add sketch utility and design kit
  package-lock.json
  packages/fast-components-react-base/src/checkbox/checkbox.tsx
  packages/fast-components-react-msft/app/app.tsx
  packages/fast-components-react-msft/app/fast-dna-msft-design-kit.sketch
  packages/fast-components-react-msft/build/create-sketch-library.js
  packages/fast-components-react-msft/package-lock.json
  packages/fast-components-react-msft/package.json
  packages/fast-components-react-msft/src/button/examples.data.tsx
  packages/fast-components-react-msft/src/divider/__snapshots__/divider.spec.ts.snap
  packages/fast-components-react-msft/src/divider/examples.data.tsx
  packages/fast-components-react-msft/src/heading/__snapshots__/heading.spec.ts.snap
  packages/fast-components-react-msft/src/heading/examples.data.tsx
  packages/fast-components-react-msft/src/hypertext/__snapshots__/hypertext.spec.ts.snap
  packages/fast-components-react-msft/src/hypertext/examples.data.tsx
  packages/fast-components-react-msft/src/label/__snapshots__/label.spec.ts.snap
  packages/fast-components-react-msft/src/label/examples.data.tsx
  packages/fast-components-react-msft/src/toggle/examples.data.tsx
  packages/fast-components-react-msft/src/typography/__snapshots__/typography.spec.ts.snap
  packages/fast-components-react-msft/src/typography/examples.data.tsx
  packages/fast-components-react-msft/webpack.config.js
  packages/fast-sketch-library/package-lock.json
  packages/fast-sketch-library/package.json
  packages/fast-sketch-library/readme.md
  packages/fast-sketch-library/src/aSketchPage.ts
  packages/fast-sketch-library/src/index.ts
  packages/fast-sketch-library/tsconfig.json
  packages/fast-sketch-library/tslint.json
  packages/fast-sketch-library/webpack.config.js
Labels: pr : feature

#496 chore(fast-layouts-react): add readme.md
  packages/fast-layouts-react/README.md
Labels: pr : chore

#505 chore(documentation): copy documentation from base to msft package
  packages/fast-components-react-msft/src/button/README.md
  packages/fast-components-react-msft/src/checkbox/README.md
  packages/fast-components-react-msft/src/divider/README.md
  packages/fast-components-react-msft/src/heading/README.md
  packages/fast-components-react-msft/src/hypertext/README.md
  packages/fast-components-react-msft/src/image/README.md
  packages/fast-components-react-msft/src/label/README.md
  packages/fast-components-react-msft/src/text-field/README.md
  packages/fast-components-react-msft/src/toggle/README.md
  packages/fast-components-react-msft/src/typography/README.md
Labels: pr : chore

#501 feat(development-site): add component for title and component for title with brand color applied
  packages/fast-components-react-base/app/index.tsx
  packages/fast-components-react-msft/app/app.tsx
  packages/fast-components-react-msft/package.json
  packages/fast-development-site-react/app/app.tsx
  packages/fast-development-site-react/app/design-system/index.ts
  packages/fast-development-site-react/src/components/site/index.tsx
  packages/fast-development-site-react/src/components/site/title-brand.tsx
  packages/fast-development-site-react/src/components/site/title.tsx
Labels: pr : feature

#509 fix(permutator): fix an issue where lodash was being referred to and not lodash-es
  packages/fast-components-react-msft/webpack.config.js
  packages/fast-permutator/__tests__/test-utils/index.js
  packages/fast-permutator/package.json
  packages/fast-permutator/src/utilities/get-deep-prop-locations.js
  packages/fast-permutator/src/utilities/get-example.js
  packages/fast-permutator/src/utilities/permutate-schemas.js
  packages/fast-permutator/src/utilities/remove-empty-objects.js
  packages/fast-permutator/src/utilities/remove-undefined.js
  packages/fast-permutator/src/utilities/resolve-all-of.js
  packages/fast-permutator/src/utilities/resolve-dependencies.js
  packages/fast-permutator/src/utilities/resolve-not-required.js
  packages/fast-permutator/src/utilities/resolve-one-of-any-of.js
  packages/fast-permutator/src/utilities/resolve-recursive-references.js
  packages/fast-permutator/src/utilities/resolve-references.js
  packages/fast-permutator/src/utilities/resolve-schema-props.js
  packages/fast-permutator/src/utilities/set-deep-object.js
Labels: pr : fix

#510 feat(components-react-msft): add favicon
  packages/fast-components-react-msft/favicon.png
  packages/fast-components-react-msft/package-lock.json
  packages/fast-components-react-msft/package.json
  packages/fast-components-react-msft/webpack.config.js
  packages/fast-development-site-react/webpack.config.js
Labels: pr : feature

#514 chore(docs): update root readme.md
  README.md
Labels: pr : chore

#515 chore: remove deprecated travis configuration
  .travis.yml
Labels: pr : chore

#516 feat(jss-manager): update to enable server-side rendering of stylesheets.
  packages/fast-jss-manager-react/README.md
  packages/fast-jss-manager-react/src/jss.ts
  packages/fast-jss-manager-react/src/manage-jss.spec.tsx
  packages/fast-jss-manager-react/src/manage-jss.tsx
  packages/fast-permutator/package-lock.json
Labels: pr : feature

#517 feat(fast-components-react-msft): add localized styles and enable ltr/rtl swapping on documentation site
  packages/fast-components-react-msft/app/app.tsx
  packages/fast-components-react-msft/package-lock.json
  packages/fast-components-styles-msft/package.json
  packages/fast-components-styles-msft/src/button/index.ts
  packages/fast-components-styles-msft/src/checkbox/index.ts
  packages/fast-components-styles-msft/src/design-system/index.ts
  packages/fast-components-styles-msft/src/toggle/index.ts
  packages/fast-development-site-react/src/components/site/index.tsx
  packages/fast-jss-utilities/src/localization.spec.ts
  packages/fast-jss-utilities/src/localization.ts
Labels: pr : feature

#518 feat(development-site): add ability to have children as strings in the form generator and development site dev tools
  packages/fast-development-site-react/src/components/site/dev-tools-code-preview.tsx
  packages/fast-form-generator-react/src/class-name-contracts/form-item.children.class-name-contract.ts
  packages/fast-form-generator-react/src/form/form-item.children.style.ts
  packages/fast-form-generator-react/src/form/form-item.children.text.tsx
  packages/fast-form-generator-react/src/form/form-item.children.tsx
  packages/fast-form-generator-react/src/form/form.tsx
  packages/fast-form-generator-react/src/utilities/form-input.style.ts
Labels: pr : feature

#522 fix(fast-development-site-react): fix the selection model to always point to a menu item
  packages/fast-development-site-react/src/components/site/index.tsx
Labels: pr : fix, reason : fixed

#525 fix(fast-development-site): fix a pathing issue between the detail and example pages
  packages/fast-development-site-react/src/components/site/action-bar.tsx
  packages/fast-development-site-react/src/components/site/index.tsx
Labels: pr : fix

#529 chore: update to bug template to provide more device options
  .github/ISSUE_TEMPLATE/Bug_report.md
Labels: pr : chore

#533 v1.8.0
  CHANGELOG.md
  lerna.json
  packages/fast-animation/CHANGELOG.md
  packages/fast-animation/package.json
  packages/fast-application-utilities/CHANGELOG.md
  packages/fast-application-utilities/package.json
  packages/fast-browser-extensions/CHANGELOG.md
  packages/fast-browser-extensions/package.json
  packages/fast-colors/CHANGELOG.md
  packages/fast-colors/package.json
  packages/fast-components-class-name-contracts-base/CHANGELOG.md
  packages/fast-components-class-name-contracts-base/package.json
  packages/fast-components-class-name-contracts-msft/CHANGELOG.md
  packages/fast-components-class-name-contracts-msft/package.json
  packages/fast-components-react-base/CHANGELOG.md
  packages/fast-components-react-base/package.json
  packages/fast-components-react-msft/CHANGELOG.md
  packages/fast-components-react-msft/package.json
  packages/fast-components-styles-msft/CHANGELOG.md
  packages/fast-components-styles-msft/package.json
  packages/fast-development-site-react/CHANGELOG.md
  packages/fast-development-site-react/package.json
  packages/fast-form-generator-react/CHANGELOG.md
  packages/fast-form-generator-react/package.json
  packages/fast-glyphs-msft/CHANGELOG.md
  packages/fast-glyphs-msft/package.json
  packages/fast-jest-snapshots-react/CHANGELOG.md
  packages/fast-jest-snapshots-react/package.json
  packages/fast-jss-manager-angular/CHANGELOG.md
  packages/fast-jss-manager-angular/package.json
  packages/fast-jss-manager-react/CHANGELOG.md
  packages/fast-jss-manager-react/package.json
  packages/fast-jss-manager/CHANGELOG.md
  packages/fast-jss-manager/package.json
  packages/fast-jss-utilities/CHANGELOG.md
  packages/fast-jss-utilities/package.json
  packages/fast-layouts-react/CHANGELOG.md
  packages/fast-layouts-react/package.json
  packages/fast-markdown-msft-react/CHANGELOG.md
  packages/fast-markdown-msft-react/package.json
  packages/fast-permutator/CHANGELOG.md
  packages/fast-permutator/package.json
  packages/fast-sketch-library/CHANGELOG.md
  packages/fast-sketch-library/package.json
  packages/fast-tslint-rules/CHANGELOG.md
  packages/fast-tslint-rules/package.json
  packages/fast-viewer-react/CHANGELOG.md
  packages/fast-viewer-react/package.json
Labels: pr : chore

#554 fix(fast-layouts-react): fix export issue to allow Column, Grid, and Page components to be imported from the root level of the package
  packages/fast-layouts-react/src/index.ts
Labels: pr : fix

#552 chore(fast-development-site-react) string formatting, styling and spacing adjustments
  packages/fast-components-react-msft/app/app.tsx
  packages/fast-development-site-react/src/components/site/category-documentation.tsx
  packages/fast-development-site-react/src/components/site/component-wrapper.tsx
  packages/fast-development-site-react/src/components/site/dev-tools-code-preview.tsx
  packages/fast-development-site-react/src/components/site/dev-tools.tsx
  packages/fast-development-site-react/src/components/site/index.tsx
  packages/fast-layouts-react/src/canvas/canvas.tsx
Labels: pr : fix

#558 feat(fast-development-site): Create infobar for fast site
  packages/fast-components-react-msft/app/app.tsx
  packages/fast-development-site-react/app/app.tsx
  packages/fast-development-site-react/src/components/shell/info-bar.tsx
  packages/fast-development-site-react/src/components/site/category.tsx
  packages/fast-development-site-react/src/components/site/index.tsx
Labels: issue : task

#559 feat(fast-development-site): add resize capability to row component
  packages/fast-development-site-react/src/components/site/index.tsx
  packages/fast-layouts-react/app/index.tsx
  packages/fast-layouts-react/src/row/row.props.ts
  packages/fast-layouts-react/src/row/row.tsx
Labels: issue : task

#568 chore(fast-jest-snapshots-react): update package to be publicly available on npm
  packages/fast-jest-snapshots-react/package.json
Labels: pr : chore

#572 chore(row): fix for row resizes on window resize
  packages/fast-layouts-react/src/row/row.tsx
Labels: issue : bug

#577 fix(fast-development-site)add scrolling to Dev Tools
  packages/fast-development-site-react/src/components/site/dev-tools.tsx
Labels: issue : bug

#573 fix(fast-development-site) Move design kit link behind Site Menu
  packages/fast-components-react-msft/app/app.tsx
  packages/fast-development-site-react/src/components/shell/header.tsx
  packages/fast-development-site-react/src/components/site/menu.tsx
Labels: issue : bug

#570 fix(fast-development-site) Update styling to config panel to match design
  packages/fast-form-generator-react/app/components/align-horizontal/__snapshots__/align-horizontal.spec.tsx.snap
  packages/fast-form-generator-react/app/components/align-vertical/__snapshots__/align-vertical.spec.tsx.snap
  packages/fast-form-generator-react/app/components/any-of/__snapshots__/any-of.spec.tsx.snap
  packages/fast-form-generator-react/app/components/attribute-assignment/__snapshots__/attribute-assignment.spec.tsx.snap
  packages/fast-form-generator-react/app/components/checkbox/__snapshots__/checkbox.spec.tsx.snap
  packages/fast-form-generator-react/app/components/number-field/__snapshots__/number-field.spec.tsx.snap
  packages/fast-form-generator-react/app/components/objects/__snapshots__/objects.spec.tsx.snap
  packages/fast-form-generator-react/app/components/one-of/__snapshots__/one-of.spec.tsx.snap
  packages/fast-form-generator-react/app/components/text-field/__snapshots__/text-field.spec.tsx.snap
  packages/fast-form-generator-react/app/components/theme/__snapshots__/theme.spec.tsx.snap
  packages/fast-form-generator-react/app/components/weight-properties/__snapshots__/weight-properties.spec.tsx.snap
  packages/fast-form-generator-react/src/class-name-contracts/form-item.align-horizontal.class-name-contract.ts
  packages/fast-form-generator-react/src/class-name-contracts/form-item.align-vertical.class-name-contract.ts
  packages/fast-form-generator-react/src/class-name-contracts/form-item.array.class-name-contract.ts
  packages/fast-form-generator-react/src/class-name-contracts/form-item.children.class-name-contract.ts
  packages/fast-form-generator-react/src/class-name-contracts/form-item.theme.class-name-contract.ts
  packages/fast-form-generator-react/src/class-name-contracts/form-section.class-name-contract.ts
  packages/fast-form-generator-react/src/form/form-item.align-horizontal.style.ts
  packages/fast-form-generator-react/src/form/form-item.align-horizontal.tsx
  packages/fast-form-generator-react/src/form/form-item.align-vertical.style.ts
  packages/fast-form-generator-react/src/form/form-item.align-vertical.tsx
  packages/fast-form-generator-react/src/form/form-item.array.style.ts
  packages/fast-form-generator-react/src/form/form-item.array.tsx
  packages/fast-form-generator-react/src/form/form-item.children.style.ts
  packages/fast-form-generator-react/src/form/form-item.children.tsx
  packages/fast-form-generator-react/src/form/form-item.textarea.style.ts
  packages/fast-form-generator-react/src/form/form-item.theme.style.ts
  packages/fast-form-generator-react/src/form/form-item.theme.tsx
  packages/fast-form-generator-react/src/form/form-section.style.ts
  packages/fast-form-generator-react/src/form/form-section.tsx
  packages/fast-form-generator-react/src/utilities/form-input.style.ts
Labels: issue : task

#579 fix(fast-development-site): remove component name and add presets tab
  packages/fast-development-site-react/src/components/site/configuration-panel.tsx
  packages/fast-development-site-react/src/components/site/index.tsx
  packages/fast-form-generator-react/app/components/align-horizontal/__snapshots__/align-horizontal.spec.tsx.snap
  packages/fast-form-generator-react/app/components/align-vertical/__snapshots__/align-vertical.spec.tsx.snap
  packages/fast-form-generator-react/app/components/any-of/__snapshots__/any-of.spec.tsx.snap
  packages/fast-form-generator-react/app/components/attribute-assignment/__snapshots__/attribute-assignment.spec.tsx.snap
  packages/fast-form-generator-react/app/components/checkbox/__snapshots__/checkbox.spec.tsx.snap
  packages/fast-form-generator-react/app/components/general-example/__snapshots__/general-example.spec.tsx.snap
  packages/fast-form-generator-react/app/components/number-field/__snapshots__/number-field.spec.tsx.snap
  packages/fast-form-generator-react/app/components/objects/__snapshots__/objects.spec.tsx.snap
  packages/fast-form-generator-react/app/components/one-of/__snapshots__/one-of.spec.tsx.snap
  packages/fast-form-generator-react/app/components/text-field/__snapshots__/text-field.spec.tsx.snap
  packages/fast-form-generator-react/app/components/theme/__snapshots__/theme.spec.tsx.snap
  packages/fast-form-generator-react/app/components/weight-properties/__snapshots__/weight-properties.spec.tsx.snap
  packages/fast-form-generator-react/src/form/form.tsx
Labels: issue : task

#583 feat(fast-development-site): add syntax highlighting to code preview
  packages/fast-development-site-react/package-lock.json
  packages/fast-development-site-react/package.json
  packages/fast-development-site-react/src/components/site/dev-tools-code-preview-style.ts
  packages/fast-development-site-react/src/components/site/dev-tools-code-preview.tsx
Labels: issue : task

#585 docs(fast-jss-manager-angular): add an example app for testing the angular JSS manager
  packages/fast-jss-manager-angular/app/app.component.ts
  packages/fast-jss-manager-angular/app/app.module.ts
  packages/fast-jss-manager-angular/app/components/example.component.ts
  packages/fast-jss-manager-angular/app/index.html
  packages/fast-jss-manager-angular/app/index.ts
  packages/fast-jss-manager-angular/app/polyfills.ts
  packages/fast-jss-manager-angular/package-lock.json
  packages/fast-jss-manager-angular/package.json
  packages/fast-jss-manager-angular/src/design-system.directive.ts
  packages/fast-jss-manager-angular/tsconfig.json
  packages/fast-jss-manager-angular/tslint.json
  packages/fast-jss-manager-angular/webpack.config.js
Labels: pr : docs

#580 docs: update README files to include missing documentation
  packages/fast-components-react-base/README.md
  packages/fast-components-react-msft/README.md
  packages/fast-components-styles-msft/README.md
  packages/fast-development-site-react/README.md
  packages/fast-form-generator-react/README.md
  packages/fast-form-generator-react/src/form/README.md
  packages/fast-glyphs-msft/README.md
  packages/fast-glyphs-msft/utilities/README.md
  packages/fast-jss-manager-angular/README.md
  packages/fast-jss-manager-react/README.md
  packages/fast-jss-manager/README.md
  packages/fast-jss-utilities/README.md
  packages/fast-markdown-msft-react/README.md
Labels: pr : docs

#601 docs: update the names of components to reflect correct casing
  packages/fast-components-react-base/src/button/__snapshots__/button.spec.ts.snap
  packages/fast-components-react-base/src/button/examples.data.tsx
  packages/fast-components-react-base/src/checkbox/__snapshots__/checkbox.spec.ts.snap
  packages/fast-components-react-base/src/checkbox/examples.data.tsx
  packages/fast-components-react-base/src/divider/__snapshots__/divider.spec.ts.snap
  packages/fast-components-react-base/src/divider/examples.data.tsx
  packages/fast-components-react-base/src/hypertext/__snapshots__/hypertext.spec.ts.snap
  packages/fast-components-react-base/src/hypertext/examples.data.tsx
  packages/fast-components-react-base/src/image/__snapshots__/image.spec.ts.snap
  packages/fast-components-react-base/src/image/examples.data.tsx
  packages/fast-components-react-base/src/label/__snapshots__/label.spec.ts.snap
  packages/fast-components-react-base/src/label/examples.data.tsx
  packages/fast-components-react-base/src/text-field/__snapshots__/text-field.spec.ts.snap
  packages/fast-components-react-base/src/text-field/examples.data.tsx
  packages/fast-components-react-base/src/toggle/__snapshots__/toggle.spec.ts.snap
  packages/fast-components-react-base/src/toggle/examples.data.tsx
  packages/fast-components-react-base/src/typography/__snapshots__/typography.spec.ts.snap
  packages/fast-components-react-base/src/typography/examples.data.tsx
  packages/fast-components-react-msft/src/button/examples.data.tsx
  packages/fast-components-react-msft/src/checkbox/examples.data.tsx
  packages/fast-components-react-msft/src/divider/__snapshots__/divider.spec.ts.snap
  packages/fast-components-react-msft/src/divider/examples.data.tsx
  packages/fast-components-react-msft/src/heading/__snapshots__/heading.spec.ts.snap
  packages/fast-components-react-msft/src/heading/examples.data.tsx
  packages/fast-components-react-msft/src/hypertext/__snapshots__/hypertext.spec.ts.snap
  packages/fast-components-react-msft/src/hypertext/examples.data.tsx
  packages/fast-components-react-msft/src/image/__snapshots__/image.spec.ts.snap
  packages/fast-components-react-msft/src/image/examples.data.tsx
  packages/fast-components-react-msft/src/label/__snapshots__/label.spec.ts.snap
  packages/fast-components-react-msft/src/label/examples.data.tsx
  packages/fast-components-react-msft/src/text-field/examples.data.tsx
  packages/fast-components-react-msft/src/toggle/examples.data.tsx
  packages/fast-components-react-msft/src/typography/__snapshots__/typography.spec.ts.snap
  packages/fast-components-react-msft/src/typography/examples.data.tsx
Labels: pr : docs

#591 feat(fast-development-site): add component transparency toggle to info bar
  packages/fast-development-site-react/README.md
  packages/fast-development-site-react/src/components/site/component-wrapper.tsx
  packages/fast-development-site-react/src/components/site/index.tsx
  packages/fast-glyphs-msft/glyphs/transparency.svg
Labels: pr : feature

#607 chore(packages): update for consistency
  package.json
  packages/fast-animation/package.json
  packages/fast-application-utilities/package.json
  packages/fast-browser-extensions/package.json
  packages/fast-colors/package.json
  packages/fast-components-class-name-contracts-base/package.json
  packages/fast-components-class-name-contracts-msft/package.json
  packages/fast-components-react-base/package.json
  packages/fast-components-react-msft/package.json
  packages/fast-components-styles-msft/package.json
  packages/fast-development-site-react/package-lock.json
  packages/fast-development-site-react/package.json
  packages/fast-form-generator-react/package.json
  packages/fast-glyphs-msft/package.json
  packages/fast-jest-snapshots-react/package.json
  packages/fast-jss-manager-angular/package-lock.json
  packages/fast-jss-manager-angular/package.json
  packages/fast-jss-manager-react/package.json
  packages/fast-jss-manager/package.json
  packages/fast-jss-utilities/package.json
  packages/fast-layouts-react/package.json
  packages/fast-markdown-msft-react/package.json
  packages/fast-permutator/package.json
  packages/fast-sketch-library/package.json
  packages/fast-tslint-rules/package.json
  packages/fast-viewer-react/package.json
Labels: pr : chore

#604 chore(fast-development-site): update class name contract for hyperlink
  packages/fast-components-react-msft/app/app.tsx
Labels: pr : chore

#606 fix(fast-development-site): update background image size
  packages/fast-development-site-react/src/components/site/component-wrapper.tsx
Labels: pr : chore

#624 chore(github): add required code owner sign-off for packages
  .github/CODEOWNERS
Labels: pr : chore
