Repository microsoft/fast, pull requests merged in 2018-07, with the labels that each got.

#627 chore(fast-markdown-msft-react): update markdown rules to reference enums
  packages/fast-components-react-msft/src/index.ts
  packages/fast-markdown-msft-react/package.json
  packages/fast-markdown-msft-react/src/index.spec.ts
  packages/fast-markdown-msft-react/src/index.ts
  packages/fast-markdown-msft-react/src/rule.ts
Labels: pr : chore

#623 docs: update CONTRIBUTING.md to include Code Owners
  CONTRIBUTING.md
Labels: pr : docs

#595 fix(fast-development-site): correctly display component view border
  packages/fast-development-site-react/src/components/site/component-wrapper.tsx
Labels: pr : fix

#634 feat(fast-development-site-react): add ability to update component values dynamically from outside the site
  packages/fast-development-site-react/src/components/site/index.tsx
Labels: pr : feature

#626 fix(fast-form-generator-react): update + glyph positioning
  packages/fast-form-generator-react/src/utilities/form-input.style.ts
Labels: pr : fix

#633 feat(fast-components-styles-msft): set default config values as a fallback if there is a missing or incomplete design system
  packages/fast-components-styles-msft/package.json
  packages/fast-components-styles-msft/src/button/index.ts
  packages/fast-components-styles-msft/src/checkbox/index.ts
  packages/fast-components-styles-msft/src/hypertext/index.ts
  packages/fast-components-styles-msft/src/text-field/index.ts
  packages/fast-components-styles-msft/src/toggle/index.ts
Labels: pr : feature

#644 fix: update imports of JSON schemas to not use * as notation
  packages/fast-components-react-base/src/button/examples.data.tsx
  packages/fast-components-react-base/src/checkbox/examples.data.tsx
  packages/fast-components-react-base/src/divider/examples.data.tsx
  packages/fast-components-react-base/src/hypertext/examples.data.tsx
  packages/fast-components-react-base/src/image/examples.data.tsx
  packages/fast-components-react-base/src/label/examples.data.tsx
  packages/fast-components-react-base/src/text-field/examples.data.tsx
  packages/fast-components-react-base/src/toggle/examples.data.tsx
  packages/fast-components-react-base/src/typography/examples.data.tsx
  packages/fast-components-react-msft/src/button/examples.data.tsx
  packages/fast-components-react-msft/src/checkbox/examples.data.tsx
  packages/fast-components-react-msft/src/divider/examples.data.tsx
  packages/fast-components-react-msft/src/heading/examples.data.tsx
  packages/fast-components-react-msft/src/hypertext/examples.data.tsx
  packages/fast-components-react-msft/src/image/examples.data.tsx
  packages/fast-components-react-msft/src/label/examples.data.tsx
  packages/fast-components-react-msft/src/text-field/examples.data.tsx
  packages/fast-components-react-msft/src/toggle/examples.data.tsx
  packages/fast-components-react-msft/src/typography/examples.data.tsx
  packages/fast-form-generator-react/app/components/index.ts
Labels: pr : fix

#647 chore: update the CSS editor to use a flattened property structure
  packages/fast-css-editor-react/.babelrc
  packages/fast-css-editor-react/.npmignore
  packages/fast-css-editor-react/README.md
  packages/fast-css-editor-react/app/app.tsx
  packages/fast-css-editor-react/app/components/editor.spec.tsx
  packages/fast-css-editor-react/src/editor.schema.json
  packages/fast-css-editor-react/src/index.tsx
  packages/fast-css-editor-react/src/position/README.md
  packages/fast-css-editor-react/src/position/position.schema.json
Labels: pr : feature

#642 feat(fast-components-react-msft): add flipper as a new component
  packages/fast-components-class-name-contracts-msft/src/flipper/index.ts
  packages/fast-components-class-name-contracts-msft/src/index.ts
  packages/fast-components-react-msft/app/examples.ts
  packages/fast-components-react-msft/src/flipper/README.md
  packages/fast-components-react-msft/src/flipper/examples.data.tsx
  packages/fast-components-react-msft/src/flipper/flipper.props.ts
  packages/fast-components-react-msft/src/flipper/flipper.schema.json
  packages/fast-components-react-msft/src/flipper/flipper.tsx
  packages/fast-components-react-msft/src/flipper/index.ts
  packages/fast-components-styles-msft/src/flipper/index.ts
  packages/fast-components-styles-msft/src/index.ts
Labels: pr : feature

#651 fix(fast-development-site): fix for component detail stretching full height when dev tools is hidden
  packages/fast-development-site-react/src/components/site/index.tsx
Labels: pr : fix

#653 fix(fast-development-site): fix devtools stretches vertically when horizontal scrollbar is visible
  packages/fast-development-site-react/src/components/site/dev-tools.tsx
Labels: pr : fix

#661 fix(divider): fix divider component so that it is styled
  packages/fast-components-styles-msft/src/divider/index.ts
Labels: pr : fix

#659 fix(checkbox): fix broken visual style and glyph in rtl
  packages/fast-components-styles-msft/src/checkbox/index.ts
Labels: pr : fix

#663 fix(toggle): toggle "Selected" option does not work and is missing background color
  packages/fast-components-react-base/package.json
  packages/fast-components-react-base/src/toggle/__snapshots__/toggle.spec.ts.snap
  packages/fast-components-react-base/src/toggle/toggle.props.ts
  packages/fast-components-react-base/src/toggle/toggle.tsx
  packages/fast-components-react-msft/src/toggle/examples.data.tsx
  packages/fast-components-styles-msft/src/toggle/index.ts
Labels: pr : fix

#655 feat(fast-development-site): add component theme support
  packages/fast-components-react-msft/app/app.tsx
  packages/fast-development-site-react/README.md
  packages/fast-development-site-react/app/app.tsx
  packages/fast-development-site-react/src/components/site/component-wrapper.tsx
  packages/fast-development-site-react/src/components/site/index.tsx
Labels: pr : feature

#677 fix(fast-form-generator-react): correct the validation between oneOf and anyOf checks
  packages/fast-form-generator-react/src/form/form-section.utilities.tsx
Labels: pr : fix

#671 chore(image): update image schema to match the current code implementation
  packages/fast-components-react-base/src/image/image.schema.json
Labels: pr : chore

#682 chore(fast-components-react-msft): add a title to the webpack app
  packages/fast-components-react-msft/webpack.config.js
Labels: pr : chore

#673 fix(fast-form-generator-react): entire list item should be clickable when navigating between sections
  packages/fast-form-generator-react/src/form/form-item.children.style.ts
  packages/fast-form-generator-react/src/utilities/form-input.style.ts
Labels: pr : fix

#680 chore(docs): correctly alphabetize docs site component links
  packages/fast-components-react-msft/app/examples.ts
Labels: pr : chore

#679 fix(label): added dark theme support for label
  packages/fast-components-styles-msft/src/label/index.ts
Labels: pr : fix

#670 chore(button): update readme documentation to specify how to create an anchor
  packages/fast-components-react-msft/src/button/README.md
Labels: pr : chore

#667 feat (fast-form-generator): update pop-up menu style, address incorrect shadowing
  packages/fast-development-site-react/src/components/toc/toc-item.tsx
  packages/fast-form-generator-react/src/form/form-item.array.style.ts
  packages/fast-form-generator-react/src/utilities/form-input.style.ts
Labels: pr : feature

#686 feat(utilities): add fast-web-utilities as a new package
  .github/CODEOWNERS
  packages/fast-web-utilities/.babelrc
  packages/fast-web-utilities/.npmignore
  packages/fast-web-utilities/README.md
  packages/fast-web-utilities/package-lock.json
  packages/fast-web-utilities/package.json
  packages/fast-web-utilities/src/dom.spec.ts
  packages/fast-web-utilities/src/dom.ts
  packages/fast-web-utilities/src/html.spec.ts
  packages/fast-web-utilities/src/html.ts
  packages/fast-web-utilities/src/index.ts
  packages/fast-web-utilities/src/key-codes.ts
  packages/fast-web-utilities/src/numbers.spec.ts
  packages/fast-web-utilities/src/numbers.ts
  packages/fast-web-utilities/src/strings.spec.ts
  packages/fast-web-utilities/src/strings.ts
  packages/fast-web-utilities/tsconfig.json
  packages/fast-web-utilities/tslint.json
Labels: pr : feature

#687 fix(fast-components-react-msft): fix error running jest with components that take a dependency on chroma-js
  packages/fast-animation/package-lock.json
  packages/fast-application-utilities/package-lock.json
  packages/fast-browser-extensions/package-lock.json
  packages/fast-colors/package-lock.json
  packages/fast-colors/src/range.ts
  packages/fast-components-class-name-contracts-base/package-lock.json
  packages/fast-components-class-name-contracts-msft/package-lock.json
  packages/fast-components-react-base/package-lock.json
  packages/fast-components-react-msft/package-lock.json
  packages/fast-components-react-msft/src/button/__snapshots__/button.spec.ts.snap
  packages/fast-components-react-msft/src/button/button.spec.ts
  packages/fast-components-react-msft/src/checkbox/__snapshots__/checkbox.spec.ts.snap
  packages/fast-components-react-msft/src/checkbox/checkbox.spec.ts
  packages/fast-components-react-msft/src/flipper/__snapshots__/flipper.spec.ts.snap
  packages/fast-components-react-msft/src/flipper/flipper.spec.ts
  packages/fast-components-react-msft/src/text-field/__snapshots__/text-field.spec.ts.snap
  packages/fast-components-react-msft/src/text-field/text-field.spec.ts
  packages/fast-components-react-msft/src/toggle/__snapshots__/toggle.spec.ts.snap
  packages/fast-components-react-msft/src/toggle/toggle.spec.ts
  packages/fast-components-styles-msft/package-lock.json
  packages/fast-components-styles-msft/src/button/index.ts
  packages/fast-components-styles-msft/src/checkbox/index.ts
  packages/fast-components-styles-msft/src/flipper/index.ts
  packages/fast-components-styles-msft/src/toggle/index.ts
  packages/fast-components-styles-msft/src/utilities/colors.ts
  packages/fast-css-editor-react/package-lock.json
  packages/fast-development-site-react/package-lock.json
  packages/fast-form-generator-react/package-lock.json
  packages/fast-glyphs-msft/package-lock.json
  packages/fast-jest-snapshots-react/package-lock.json
  packages/fast-jss-manager-angular/package-lock.json
  packages/fast-jss-manager-react/package-lock.json
  packages/fast-jss-manager/package-lock.json
  packages/fast-jss-utilities/package-lock.json
  packages/fast-layouts-react/package-lock.json
  packages/fast-markdown-msft-react/package-lock.json
  packages/fast-permutator/package-lock.json
  packages/fast-sketch-library/package-lock.json
  packages/fast-tslint-rules/package-lock.json
  packages/fast-viewer-react/package-lock.json
Labels: pr : fix

#683 fix(fast-form-generator-react): sets the value of the textarea to an empty string if it is undefined
  packages/fast-form-generator-react/app/components/any-of/__snapshots__/any-of.spec.tsx.snap
  packages/fast-form-generator-react/app/components/one-of/__snapshots__/one-of.spec.tsx.snap
  packages/fast-form-generator-react/src/form/form-item.textarea.tsx
Labels: pr : fix

#689 fix(toggle): fix labels on toggle to support dark theme
  packages/fast-components-styles-msft/src/toggle/index.ts
Labels: pr : fix

#697 fix(fast-development-site): fixes site component issue where state is expected for theme even if it does not exist
  packages/fast-development-site-react/src/components/site/index.tsx
Labels: pr : fix

#700 v1.9.2
  lerna.json
  packages/fast-animation/package.json
  packages/fast-application-utilities/package.json
  packages/fast-browser-extensions/package.json
  packages/fast-colors/package.json
  packages/fast-components-class-name-contracts-base/package.json
  packages/fast-components-class-name-contracts-msft/package.json
  packages/fast-components-react-base/package.json
  packages/fast-components-react-msft/package.json
  packages/fast-components-styles-msft/package.json
  packages/fast-css-editor-react/package.json
  packages/fast-development-site-react/package.json
  packages/fast-form-generator-react/package.json
  packages/fast-glyphs-msft/package.json
  packages/fast-jest-snapshots-react/package.json
  packages/fast-jss-manager-angular/package.json
  packages/fast-jss-manager-react/package.json
  packages/fast-jss-manager/package.json
  packages/fast-jss-utilities/package.json
  packages/fast-layouts-react/package.json
  packages/fast-markdown-msft-react/package.json
  packages/fast-permutator/package.json
  packages/fast-sketch-library/package.json
  packages/fast-tslint-rules/package.json
  packages/fast-viewer-react/package.json
  packages/fast-web-utilities/package.json
Labels: pr : chore

#707 fix(fast-css-editor-react): update the api to accept strings for position
  packages/fast-css-editor-react/app/app.tsx
  packages/fast-css-editor-react/app/components/position.spec.tsx
  packages/fast-css-editor-react/src/editor.schema.json
  packages/fast-css-editor-react/src/position/README.md
  packages/fast-css-editor-react/src/position/index.tsx
  packages/fast-css-editor-react/src/position/position.schema.json
Labels: pr : breaking change :boom:

#699 feat(fast-components-react-base): add unit tests to all components and update code coverage expectations
  packages/fast-components-react-base/package-lock.json
  packages/fast-components-react-base/package.json
  packages/fast-components-react-base/src/button/__snapshots__/button.spec.tsx.snap
  packages/fast-components-react-base/src/button/button.spec.ts
  packages/fast-components-react-base/src/button/button.spec.tsx
  packages/fast-components-react-base/src/checkbox/__snapshots__/checkbox.spec.tsx.snap
  packages/fast-components-react-base/src/checkbox/checkbox.spec.ts
  packages/fast-components-react-base/src/checkbox/checkbox.spec.tsx
  packages/fast-components-react-base/src/divider/__snapshots__/divider.spec.tsx.snap
  packages/fast-components-react-base/src/divider/divider.spec.ts
  packages/fast-components-react-base/src/divider/divider.spec.tsx
  packages/fast-components-react-base/src/hypertext/__snapshots__/hypertext.spec.tsx.snap
  packages/fast-components-react-base/src/hypertext/hypertext.spec.ts
  packages/fast-components-react-base/src/hypertext/hypertext.spec.tsx
  packages/fast-components-react-base/src/image/__snapshots__/image.spec.tsx.snap
  packages/fast-components-react-base/src/image/examples.data.tsx
  packages/fast-components-react-base/src/image/image.props.ts
  packages/fast-components-react-base/src/image/image.spec.ts
  packages/fast-components-react-base/src/image/image.spec.tsx
  packages/fast-components-react-base/src/image/image.tsx
  packages/fast-components-react-base/src/label/__snapshots__/label.spec.tsx.snap
  packages/fast-components-react-base/src/label/label.spec.ts
  packages/fast-components-react-base/src/label/label.spec.tsx
  packages/fast-components-react-base/src/text-field/__snapshots__/text-field.spec.tsx.snap
  packages/fast-components-react-base/src/text-field/text-field.spec.ts
  packages/fast-components-react-base/src/text-field/text-field.spec.tsx
  packages/fast-components-react-base/src/toggle/__snapshots__/toggle.spec.tsx.snap
  packages/fast-components-react-base/src/toggle/toggle.spec.ts
  packages/fast-components-react-base/src/toggle/toggle.spec.tsx
  packages/fast-components-react-base/src/typography/__snapshots__/typography.spec.tsx.snap
  packages/fast-components-react-base/src/typography/typography.spec.ts
  packages/fast-components-react-base/src/typography/typography.spec.tsx
Labels: pr : feature

#657 fix(label): remove label element shift when changing HTML type in configure pane
  packages/fast-components-styles-msft/src/label/index.ts
Labels: pr : chore

#715 fix(fast-development-site): text cursor for non interactable areas should be default cursor
  packages/fast-development-site-react/src/components/shell/info-bar.tsx
  packages/fast-development-site-react/src/components/site/index.tsx
Labels: pr : fix

#732 feat(fast-components-react-msft): add enzyme and unit tests for MSFT specific components
  packages/fast-components-react-msft/package-lock.json
  packages/fast-components-react-msft/package.json
  packages/fast-components-react-msft/src/button/__snapshots__/button.spec.tsx.snap
  packages/fast-components-react-msft/src/button/button.spec.ts
  packages/fast-components-react-msft/src/button/button.spec.tsx
  packages/fast-components-react-msft/src/checkbox/__snapshots__/checkbox.spec.ts.snap
  packages/fast-components-react-msft/src/checkbox/checkbox.spec.ts
  packages/fast-components-react-msft/src/divider/__snapshots__/divider.spec.ts.snap
  packages/fast-components-react-msft/src/divider/divider.spec.ts
  packages/fast-components-react-msft/src/flipper/__snapshots__/flipper.spec.tsx.snap
  packages/fast-components-react-msft/src/flipper/flipper.spec.ts
  packages/fast-components-react-msft/src/flipper/flipper.spec.tsx
  packages/fast-components-react-msft/src/heading/__snapshots__/heading.spec.tsx.snap
  packages/fast-components-react-msft/src/heading/heading.spec.ts
  packages/fast-components-react-msft/src/heading/heading.spec.tsx
  packages/fast-components-react-msft/src/hypertext/__snapshots__/hypertext.spec.ts.snap
  packages/fast-components-react-msft/src/hypertext/hypertext.spec.ts
  packages/fast-components-react-msft/src/image/__snapshots__/image.spec.ts.snap
  packages/fast-components-react-msft/src/image/image.spec.ts
  packages/fast-components-react-msft/src/label/__snapshots__/label.spec.ts.snap
  packages/fast-components-react-msft/src/label/label.spec.ts
  packages/fast-components-react-msft/src/text-field/__snapshots__/text-field.spec.ts.snap
  packages/fast-components-react-msft/src/text-field/text-field.spec.ts
  packages/fast-components-react-msft/src/toggle/__snapshots__/toggle.spec.ts.snap
  packages/fast-components-react-msft/src/toggle/toggle.spec.ts
  packages/fast-components-react-msft/src/typography/__snapshots__/typography.spec.ts.snap
  packages/fast-components-react-msft/src/typography/typography.spec.ts
Labels: pr : feature

#703 fix(button): update to use enum for button types
  packages/fast-components-react-msft/README.md
  packages/fast-components-react-msft/src/button/button.props.ts
  packages/fast-components-react-msft/src/button/button.schema.json
  packages/fast-components-react-msft/src/button/button.spec.tsx
  packages/fast-components-react-msft/src/button/button.tsx
  packages/fast-components-react-msft/src/button/examples.data.tsx
Labels: pr : breaking change :boom:, pr : fix

#727 fix(fast-form-generator): remove resize behavior and update fontfamily
  packages/fast-form-generator-react/src/form/form-item.textarea.style.ts
Labels: pr : fix

#735 feat: remove node sass from fast-animations
  packages/fast-animation/client/examples/app/assets/styles/test-page.css
  packages/fast-animation/client/examples/app/assets/styles/test-page.scss
  packages/fast-animation/client/examples/app/components/TestPage.tsx
  packages/fast-animation/package-lock.json
  packages/fast-animation/package.json
  packages/fast-animation/webpack/webpack.common.config.js
Labels: pr : feature

#743 chore(tests): fix failing unit tests in fast-jss-manager and fast-layouts-react
  .circleci/config.yml
  packages/fast-layouts-react/src/foundation/foundation.spec.ts
  packages/fast-layouts-react/src/utilities/breakpoint-tracker.spec.ts
  packages/fast-layouts-react/src/utilities/breakpoints.spec.ts
Labels: pr : chore

#740 feat(utilities): adds generic acrylic function to `fast-jss-utilites` and MSFT specific implementation to `fast-component-styles-msft`
  packages/fast-components-styles-msft/src/index.ts
  packages/fast-components-styles-msft/src/utilities/acrylic.ts
  packages/fast-jss-utilities/README.md
  packages/fast-jss-utilities/src/acrylic.ts
  packages/fast-jss-utilities/src/direction.ts
  packages/fast-jss-utilities/src/index.ts
Labels: pr : feature

#739 feat(fast-components-react-base): add horizontal overflow
  packages/fast-components-class-name-contracts-base/src/horizontal-overflow/index.ts
  packages/fast-components-class-name-contracts-base/src/index.ts
  packages/fast-components-react-base/app/examples.ts
  packages/fast-components-react-base/package-lock.json
  packages/fast-components-react-base/package.json
  packages/fast-components-react-base/src/horizontal-overflow/README.md
  packages/fast-components-react-base/src/horizontal-overflow/__snapshots__/horizontal-overflow.spec.tsx.snap
  packages/fast-components-react-base/src/horizontal-overflow/examples.data.tsx
  packages/fast-components-react-base/src/horizontal-overflow/horizontal-overflow.node.spec.tsx
  packages/fast-components-react-base/src/horizontal-overflow/horizontal-overflow.props.ts
  packages/fast-components-react-base/src/horizontal-overflow/horizontal-overflow.schema.json
  packages/fast-components-react-base/src/horizontal-overflow/horizontal-overflow.spec.tsx
  packages/fast-components-react-base/src/horizontal-overflow/horizontal-overflow.tsx
  packages/fast-components-react-base/src/horizontal-overflow/index.ts
  packages/fast-components-react-base/src/index.ts
Labels: pr : feature

#691 fix(hypertext): update foreground to use design system colors for theming support
  packages/fast-components-styles-msft/src/hypertext/index.ts
Labels: pr : fix
