Repository microsoft/fast, pull requests merged in 2018-04, with the labels that each got.

#188 fix(tslint): fixes incorrect tslint rule regarding ordered imports
  .codeclimate.yml
  packages/fast-animation/client/examples/app/app.tsx
  packages/fast-browser-extensions/src/extension/ExtensionApi/ContextMenuApi/index.ts
  packages/fast-browser-extensions/src/extension/ExtensionApi/RuntimeApi/on-message-external.ts
  packages/fast-browser-extensions/src/extension/ExtensionApi/TabsApi/index.ts
  packages/fast-browser-extensions/src/extension/content.ts
  packages/fast-browser-extensions/src/extension/contextMenu/index.ts
  packages/fast-browser-extensions/src/extension/manifest.ts
  packages/fast-browser-extensions/src/extension/messaging/index.ts
  packages/fast-components-react-base/app/index.tsx
  packages/fast-components-react-base/src/button/Button.tsx
  packages/fast-components-react-base/src/button/examples.data.ts
  packages/fast-components-react-base/src/foundation/Foundation.spec.tsx
  packages/fast-components-react-base/src/foundation/Foundation.ts
  packages/fast-components-react-msft/app/index.tsx
  packages/fast-components-react-msft/src/button/index.ts
  packages/fast-development-site-react/app/app.tsx
  packages/fast-development-site-react/src/components/breadcrumb/breadcrumb-item.tsx
  packages/fast-development-site-react/src/components/breadcrumb/index.tsx
  packages/fast-development-site-react/src/components/shell/action-bar.tsx
  packages/fast-development-site-react/src/components/shell/canvas.tsx
  packages/fast-development-site-react/src/components/shell/header.tsx
  packages/fast-development-site-react/src/components/shell/index.tsx
  packages/fast-development-site-react/src/components/shell/pane.tsx
  packages/fast-development-site-react/src/components/shell/row.tsx
  packages/fast-development-site-react/src/components/site/category-item.tsx
  packages/fast-development-site-react/src/components/site/index.tsx
  packages/fast-jss-manager-angular/src/design-system.directive.ts
  packages/fast-jss-manager-angular/src/design-system.module.ts
  packages/fast-jss-manager-angular/src/jss.ts
  packages/fast-jss-manager-angular/src/manage-jss.test.ts
  packages/fast-jss-manager-angular/src/manage-jss.ts
  packages/fast-jss-manager-angular/src/utilities/get-static-styles.ts
  packages/fast-jss-manager-react/src/jss.ts
  packages/fast-jss-manager-react/src/manage-jss.spec.tsx
  packages/fast-jss-manager-react/src/manage-jss.tsx
  packages/fast-jss-manager-react/src/utilities/get-static-styles.ts
  packages/fast-jss-manager-react/src/utilities/object.spec.ts
  packages/fast-jss-manager/src/index.ts
  packages/fast-tslint-rules/tslint.json
  packages/fast-viewer-react/app/components/page.tsx
  packages/fast-viewer-react/src/components/index.ts
  packages/fast-viewer-react/src/components/viewer/index.tsx
Labels: type : fix

#163 devops: add test coverage
  .codeclimate.yml
  .travis.yml
  package-lock.json
  package.json
  packages/fast-animation/package.json
  packages/fast-colors/package.json
  packages/fast-components-react-base/package.json
  packages/fast-components-react-msft/package.json
  packages/fast-components-styles-msft/package.json
  packages/fast-development-site-react/package.json
  packages/fast-jss-manager-angular/package.json
  packages/fast-jss-manager-react/package.json
  packages/fast-jss-manager/package.json
  packages/fast-permutator/package.json
  packages/fast-tslint-rules/package.json
  packages/fast-viewer-react/package.json
Labels: task : create, type : devops

#186 feat: catagorizing relevant dependencies as peerDependencies
  packages/fast-animation/lib/triggers/ScrollBase.ts
  packages/fast-animation/package-lock.json
  packages/fast-animation/package.json
  packages/fast-colors/package.json
  packages/fast-components-react-base/.npmignore
  packages/fast-components-react-base/package.json
  packages/fast-components-react-msft/package.json
  packages/fast-development-site-react/package.json
  packages/fast-jss-manager-angular/package.json
  packages/fast-jss-manager-angular/src/manage-jss.ts
  packages/fast-jss-manager-react/.babelrc
  packages/fast-jss-manager-react/.npmignore
  packages/fast-jss-manager-react/package-lock.json
  packages/fast-jss-manager-react/package.json
  packages/fast-jss-manager-react/src/manage-jss.tsx
  packages/fast-permutator/package.json
  packages/fast-tslint-rules/package.json
Labels: type : feat

#208 build: adds new script to clean package lock files
  build/clean-package-locks.js
  packages/fast-animation/package-lock.json
  packages/fast-browser-extensions/package-lock.json
  packages/fast-colors/package-lock.json
  packages/fast-components-react-base/package-lock.json
  packages/fast-components-react-msft/package-lock.json
  packages/fast-development-site-react/package-lock.json
  packages/fast-jest-snapshots-react/package-lock.json
  packages/fast-jss-manager-angular/package-lock.json
  packages/fast-jss-manager-react/package-lock.json
  packages/fast-permutator/package-lock.json
  packages/fast-viewer-react/package-lock.json
Labels: task : create, type : build

#198 readme: updates fast-permutator documentation
  packages/fast-permutator/README.md
Labels: task : update, type : docs

#215 docs(readme): add badges for package quality, activity, contributors, and license
  README.md
  packages/fast-animation/README.md
Labels: task : create, type : docs

#238 docs: remove total contributors and commit badges
  README.md
Labels: task : update, type : docs

#212 feat(toggle): add new component and msft styles
  .gitignore
  package-lock.json
  packages/fast-animation/package-lock.json
  packages/fast-browser-extensions/package-lock.json
  packages/fast-colors/package-lock.json
  packages/fast-components-class-name-contracts/package-lock.json
  packages/fast-components-class-name-contracts/src/index.ts
  packages/fast-components-class-name-contracts/src/toggle/index.ts
  packages/fast-components-react-base/app/examples.ts
  packages/fast-components-react-base/package-lock.json
  packages/fast-components-react-base/src/index.ts
  packages/fast-components-react-base/src/toggle/DOCS.MD
  packages/fast-components-react-base/src/toggle/__snapshots__/toggle.spec.ts.snap
  packages/fast-components-react-base/src/toggle/examples.data.ts
  packages/fast-components-react-base/src/toggle/index.ts
  packages/fast-components-react-base/src/toggle/toggle.props.ts
  packages/fast-components-react-base/src/toggle/toggle.spec.ts
  packages/fast-components-react-base/src/toggle/toggle.tsx
  packages/fast-components-react-msft/app/examples.ts
  packages/fast-components-react-msft/package-lock.json
  packages/fast-components-react-msft/src/index.ts
  packages/fast-components-react-msft/src/toggle/examples.data.ts
  packages/fast-components-react-msft/src/toggle/index.ts
  packages/fast-components-styles-msft/package-lock.json
  packages/fast-components-styles-msft/package.json
  packages/fast-components-styles-msft/src/index.ts
  packages/fast-components-styles-msft/src/toggle/index.ts
  packages/fast-development-site-react/package-lock.json
  packages/fast-glyphs-msft/package-lock.json
  packages/fast-jest-snapshots-react/package-lock.json
  packages/fast-jss-manager-angular/package-lock.json
  packages/fast-jss-manager-react/package-lock.json
  packages/fast-jss-manager/package-lock.json
  packages/fast-permutator/package-lock.json
  packages/fast-tslint-rules/package-lock.json
  packages/fast-viewer-react/package-lock.json
Labels: task : create, type : feat

#247 feat(typography): add typography as a new base component and style
  packages/fast-components-class-name-contracts/src/index.ts
  packages/fast-components-class-name-contracts/src/typography/index.ts
  packages/fast-components-react-base/app/examples.ts
  packages/fast-components-react-base/src/index.ts
  packages/fast-components-react-base/src/typography/__snapshots__/typography.spec.ts.snap
  packages/fast-components-react-base/src/typography/examples.data.ts
  packages/fast-components-react-base/src/typography/index.ts
  packages/fast-components-react-base/src/typography/typography.props.ts
  packages/fast-components-react-base/src/typography/typography.spec.ts
  packages/fast-components-react-base/src/typography/typography.tsx
  packages/fast-components-react-msft/app/examples.ts
  packages/fast-components-react-msft/src/typography/examples.data.ts
  packages/fast-components-react-msft/src/typography/index.ts
  packages/fast-components-styles-msft/src/index.ts
  packages/fast-components-styles-msft/src/typography/index.ts
  packages/fast-components-styles-msft/src/utilities/keyof-to-type.ts
  packages/fast-components-styles-msft/src/utilities/typography.ts
Labels: task : create, type : feat

#251 feat: update to React 16.3
  package-lock.json
  packages/fast-components-react-base/package.json
  packages/fast-components-react-msft/package.json
  packages/fast-development-site-react/package.json
  packages/fast-jest-snapshots-react/package.json
  packages/fast-jss-manager-react/package.json
  packages/fast-viewer-react/package.json
Labels: task : update, type : feat

#257 update(base): update base components to use lodash get method to access managed classes
  packages/fast-components-react-base/src/button/button.tsx
  packages/fast-components-react-base/src/divider/divider.tsx
  packages/fast-components-react-base/src/image/image.tsx
  packages/fast-components-react-base/src/toggle/toggle.tsx
Labels: task : update, type : refactor

#261 fix(tests): fix polymer issue during lerna run test
  packages/fast-development-site-react/app/components/polymer-heading.ts
  packages/fast-development-site-react/package-lock.json
  packages/fast-development-site-react/package.json
Labels: type : fix

#210 feat: add hypertext component
  packages/fast-components-class-name-contracts-base/src/hypertext/index.ts
  packages/fast-components-class-name-contracts-base/src/index.ts
  packages/fast-components-react-base/app/examples.ts
  packages/fast-components-react-base/src/hypertext/DOCS.md
  packages/fast-components-react-base/src/hypertext/__snapshots__/hypertext.spec.ts.snap
  packages/fast-components-react-base/src/hypertext/examples.data.ts
  packages/fast-components-react-base/src/hypertext/hypertext.props.ts
  packages/fast-components-react-base/src/hypertext/hypertext.spec.ts
  packages/fast-components-react-base/src/hypertext/hypertext.tsx
  packages/fast-components-react-base/src/hypertext/index.ts
  packages/fast-components-react-base/src/index.ts
  packages/fast-components-react-msft/app/examples.ts
  packages/fast-components-react-msft/src/hypertext/examples.data.ts
  packages/fast-components-react-msft/src/hypertext/index.ts
  packages/fast-components-react-msft/src/index.ts
  packages/fast-components-styles-msft/src/hypertext/index.ts
  packages/fast-components-styles-msft/src/index.ts
Labels: task : create, type : feat

#260 refactor: remove instances of uuid in favor of lodash uniqueId in react packages
  packages/fast-development-site-react/package-lock.json
  packages/fast-development-site-react/package.json
  packages/fast-development-site-react/src/components/site/index.tsx
  packages/fast-jss-manager-angular/.babelrc
  packages/fast-jss-manager-angular/.npmignore
  packages/fast-jss-manager-angular/package-lock.json
  packages/fast-jss-manager-angular/package.json
  packages/fast-jss-manager-angular/src/manage-jss.ts
  packages/fast-jss-manager-react/package.json
  packages/fast-jss-manager-react/src/manage-jss.tsx
Labels: task : update, type : refactor

#266 doc(props): update props documentation for consistency
  packages/fast-components-react-base/src/button/button.props.ts
  packages/fast-components-react-base/src/divider/divider.props.ts
  packages/fast-components-react-base/src/foundation/foundation.props.ts
  packages/fast-components-react-base/src/hypertext/hypertext.props.ts
  packages/fast-components-react-base/src/toggle/toggle.props.ts
  packages/fast-components-react-base/src/typography/typography.props.ts
Labels: task : create, type : docs

#268 refactor(viewer): refactor viewer to reduce cognitive complexity and duplicate code
  packages/fast-animation/package-lock.json
  packages/fast-browser-extensions/package-lock.json
  packages/fast-colors/package-lock.json
  packages/fast-components-class-name-contracts-base/package-lock.json
  packages/fast-components-class-name-contracts-msft/package-lock.json
  packages/fast-components-react-base/package-lock.json
  packages/fast-components-react-msft/package-lock.json
  packages/fast-components-styles-msft/package-lock.json
  packages/fast-development-site-react/package-lock.json
  packages/fast-glyphs-msft/package-lock.json
  packages/fast-jest-snapshots-react/package-lock.json
  packages/fast-jss-manager-angular/package-lock.json
  packages/fast-jss-manager-react/package-lock.json
  packages/fast-jss-manager/package-lock.json
  packages/fast-permutator/package-lock.json
  packages/fast-tslint-rules/package-lock.json
  packages/fast-viewer-react/.babelrc
  packages/fast-viewer-react/.npmignore
  packages/fast-viewer-react/package-lock.json
  packages/fast-viewer-react/package.json
  packages/fast-viewer-react/src/components/viewer/index.tsx
Labels: task : update, type : refactor

#252 feat(checkbox): add new component with styles
  .gitignore
  package-lock.json
  packages/fast-animation/package-lock.json
  packages/fast-browser-extensions/package-lock.json
  packages/fast-components-class-name-contracts-base/src/checkbox/index.ts
  packages/fast-components-class-name-contracts-base/src/index.ts
  packages/fast-components-react-base/app/examples.ts
  packages/fast-components-react-base/package-lock.json
  packages/fast-components-react-base/src/checkbox/DOCS.md
  packages/fast-components-react-base/src/checkbox/README.md
  packages/fast-components-react-base/src/checkbox/__snapshots__/checkbox.spec.ts.snap
  packages/fast-components-react-base/src/checkbox/checkbox.props.ts
  packages/fast-components-react-base/src/checkbox/checkbox.spec.ts
  packages/fast-components-react-base/src/checkbox/checkbox.tsx
  packages/fast-components-react-base/src/checkbox/examples.data.ts
  packages/fast-components-react-base/src/checkbox/index.ts
  packages/fast-components-react-base/src/index.ts
  packages/fast-components-react-msft/app/examples.ts
  packages/fast-components-react-msft/package-lock.json
  packages/fast-components-react-msft/src/checkbox/examples.data.ts
  packages/fast-components-react-msft/src/checkbox/index.ts
  packages/fast-components-react-msft/src/index.ts
  packages/fast-components-styles-msft/src/checkbox/index.ts
  packages/fast-components-styles-msft/src/index.ts
  packages/fast-development-site-react/package-lock.json
  packages/fast-viewer-react/package-lock.json
Labels: task : create, type : feat

#282 feat(jss-manager-react): add stylesheet overrides as props
  packages/fast-components-react-msft/src/button/index.ts
  packages/fast-components-react-msft/src/checkbox/index.ts
  packages/fast-components-react-msft/src/divider/index.ts
  packages/fast-components-react-msft/src/hypertext/index.ts
  packages/fast-components-react-msft/src/image/index.ts
  packages/fast-components-react-msft/src/label/index.ts
  packages/fast-components-react-msft/src/toggle/index.ts
  packages/fast-components-react-msft/src/typography/index.ts
  packages/fast-development-site-react/src/components/breadcrumb/breadcrumb-item.tsx
  packages/fast-development-site-react/src/components/breadcrumb/index.tsx
  packages/fast-development-site-react/src/components/shell/action-bar.tsx
  packages/fast-development-site-react/src/components/shell/canvas.tsx
  packages/fast-development-site-react/src/components/shell/header.tsx
  packages/fast-development-site-react/src/components/shell/index.tsx
  packages/fast-development-site-react/src/components/shell/info-bar.tsx
  packages/fast-development-site-react/src/components/shell/pane-collapse.tsx
  packages/fast-development-site-react/src/components/shell/pane.tsx
  packages/fast-development-site-react/src/components/shell/row.tsx
  packages/fast-development-site-react/src/components/site/category-item.tsx
  packages/fast-development-site-react/src/components/site/index.tsx
  packages/fast-development-site-react/src/components/site/menu.tsx
  packages/fast-development-site-react/src/components/toc/index.tsx
  packages/fast-development-site-react/src/components/toc/toc-item.tsx
  packages/fast-development-site-react/src/components/toc/toc-menu.tsx
  packages/fast-jss-manager-react/README.md
  packages/fast-jss-manager-react/package-lock.json
  packages/fast-jss-manager-react/package.json
  packages/fast-jss-manager-react/src/manage-jss.spec.tsx
  packages/fast-jss-manager-react/src/manage-jss.tsx
  packages/fast-jss-manager-react/src/utilities/get-static-styles.ts
Labels: task : update, type : feat

#308 feat: update utility to include localized spacing and direction
  packages/fast-components-react-msft/package-lock.json
  packages/fast-components-styles-msft/package-lock.json
  packages/fast-jss-utilities/package-lock.json
  packages/fast-jss-utilities/package.json
  packages/fast-jss-utilities/src/direction.ts
  packages/fast-jss-utilities/src/localization.spec.ts
  packages/fast-jss-utilities/src/localization.ts
  packages/fast-jss-utilities/tsconfig.json
Labels: task : update, type : feat

#321 refactor(hypertext): remove code duplication in hypertext styles
  packages/fast-components-styles-msft/src/hypertext/index.ts
Labels: issue, reason : fixed

#323 fix(permutator): fix duplicate code for handling required and optional data
  packages/fast-permutator/src/index.js
  packages/fast-permutator/src/utilities/get-example.js
Labels: issue, reason : fixed

#325 fix(animation): refactor animate sequence and group to remove code duplication
  packages/fast-animation/client/examples/app/components/TestPage.tsx
  packages/fast-animation/lib/animateGroup/index.ts
  packages/fast-animation/lib/animateSequence/index.ts
  packages/fast-animation/lib/utilities/invokeFunctionForEach.ts
Labels: issue, reason : fixed

#327 fix(permutator): refactor repeated code to check if a location is recursive into a new utility
  packages/fast-permutator/src/utilities/get-deep-prop-locations.js
  packages/fast-permutator/src/utilities/is-location-recursive.js
  packages/fast-permutator/src/utilities/resolve-recursive-references.js
Labels: issue, reason : fixed

#332 refactor(jss-manager): refactor react JSS Manager to remove stylesheet separation and treat all styles as dynamic
  packages/fast-animation/package-lock.json
  packages/fast-browser-extensions/package-lock.json
  packages/fast-colors/package-lock.json
  packages/fast-components-class-name-contracts-base/package-lock.json
  packages/fast-components-class-name-contracts-msft/package-lock.json
  packages/fast-components-react-base/package-lock.json
  packages/fast-components-react-msft/package-lock.json
  packages/fast-components-react-msft/src/heading/__snapshots__/heading.spec.ts.snap
  packages/fast-components-styles-msft/package-lock.json
  packages/fast-development-site-react/package-lock.json
  packages/fast-glyphs-msft/package-lock.json
  packages/fast-jest-snapshots-react/package-lock.json
  packages/fast-jss-manager-angular/package-lock.json
  packages/fast-jss-manager-react/package-lock.json
  packages/fast-jss-manager-react/package.json
  packages/fast-jss-manager-react/src/manage-jss.spec.tsx
  packages/fast-jss-manager-react/src/manage-jss.tsx
  packages/fast-jss-manager-react/src/utilities/get-static-styles.ts
  packages/fast-jss-manager/package-lock.json
  packages/fast-jss-utilities/package-lock.json
  packages/fast-permutator/package-lock.json
  packages/fast-tslint-rules/package-lock.json
  packages/fast-viewer-react/package-lock.json
Labels: task : update, type : refactor

#336 fix: travis-CI build-break
  package-lock.json
  packages/fast-animation/package-lock.json
  packages/fast-browser-extensions/package-lock.json
  packages/fast-colors/package-lock.json
  packages/fast-components-class-name-contracts-base/package-lock.json
  packages/fast-components-class-name-contracts-msft/package-lock.json
  packages/fast-components-react-base/package-lock.json
  packages/fast-components-react-msft/package-lock.json
  packages/fast-components-styles-msft/package-lock.json
  packages/fast-development-site-react/package-lock.json
  packages/fast-development-site-react/package.json
  packages/fast-glyphs-msft/package-lock.json
  packages/fast-jest-snapshots-react/package-lock.json
  packages/fast-jss-manager-angular/package-lock.json
  packages/fast-jss-manager-react/package-lock.json
  packages/fast-jss-manager/package-lock.json
  packages/fast-jss-utilities/package-lock.json
  packages/fast-permutator/package-lock.json
  packages/fast-tslint-rules/package-lock.json
  packages/fast-viewer-react/package-lock.json
  packages/fast-viewer-react/package.json
Labels: issue, reason : fixed

#338 refactor(jss-manager): refactor react JSS Manager to treat all styles as dynamic
  packages/fast-components-react-msft/src/heading/__snapshots__/heading.spec.ts.snap
  packages/fast-jss-manager-react/package.json
  packages/fast-jss-manager-react/src/manage-jss.spec.tsx
  packages/fast-jss-manager-react/src/manage-jss.tsx
  packages/fast-jss-manager-react/src/utilities/get-static-styles.ts
Labels: task : update, type : feat

#340 refactor(jss-manager-angular): refactor angular jss manager to remove static stylesheet and treat all styles as dynamic
  packages/fast-jss-manager-angular/package.json
  packages/fast-jss-manager-angular/src/manage-jss.test.ts
  packages/fast-jss-manager-angular/src/manage-jss.ts
  packages/fast-jss-manager-angular/src/utilities/get-static-styles.test.ts
  packages/fast-jss-manager-angular/src/utilities/get-static-styles.ts
  packages/fast-jss-manager-angular/src/utilities/object.ts
  packages/fast-jss-manager-react/src/utilities/object.spec.ts
  packages/fast-jss-manager-react/src/utilities/object.ts
Labels: task : update, type : feat

#343 feat: add tabbed navigation for development site
  packages/fast-components-react-msft/webpack.config.js
  packages/fast-development-site-react/package-lock.json
  packages/fast-development-site-react/package.json
  packages/fast-development-site-react/src/components/site/action-bar.tsx
  packages/fast-development-site-react/src/components/site/component-view-toggle.tsx
  packages/fast-development-site-react/src/components/site/component-view.tsx
  packages/fast-development-site-react/src/components/site/index.tsx
  packages/fast-glyphs-msft/glyphs/examples.svg
  packages/fast-glyphs-msft/glyphs/page.svg
Labels: type : feat

#314 feat(button): updates to current msft styles
  packages/fast-components-class-name-contracts-msft/src/button/index.ts
  packages/fast-components-class-name-contracts-msft/src/index.ts
  packages/fast-components-react-base/src/button/button.props.ts
  packages/fast-components-react-base/src/button/button.tsx
  packages/fast-components-react-msft/src/button/button.props.ts
  packages/fast-components-react-msft/src/button/button.tsx
  packages/fast-components-react-msft/src/button/examples.data.ts
  packages/fast-components-react-msft/src/button/index.ts
  packages/fast-components-styles-msft/src/button/index.ts
  packages/fast-form-generator-react/package-lock.json
  packages/fast-jss-utilities/src/index.ts
Labels: task : update, type : feat

#346 feat(markdown): add utility to convert markdown to msft component strings
  packages/fast-form-generator-react/src/form/README.md
  packages/fast-markdown-msft-react/.babelrc
  packages/fast-markdown-msft-react/.npmignore
  packages/fast-markdown-msft-react/README.md
  packages/fast-markdown-msft-react/package-lock.json
  packages/fast-markdown-msft-react/package.json
  packages/fast-markdown-msft-react/src/index.spec.ts
  packages/fast-markdown-msft-react/src/index.ts
  packages/fast-markdown-msft-react/src/rule.ts
  packages/fast-markdown-msft-react/tsconfig.json
  packages/fast-markdown-msft-react/tslint.json
Labels: task : create, type : feat
