Repository microsoft/fast, pull requests merged in 2020-11, with the labels that each got.

#4089 chore: remove elevated-corner-radius which was not in use
  packages/web-components/fast-components/src/design-system-provider/README.md
  packages/web-components/fast-components/src/menu/menu.styles.ts
Labels: chore

#4098 fix: updated the background on attribute dropdown in fast tooling used in component explorer
  packages/tooling/fast-tooling-react/app/pages/form.tsx
  packages/tooling/fast-tooling-react/src/form/controls/control.select.style.ts
  packages/tooling/fast-tooling-react/src/style/css-properties.ts
Labels: area:tools, bug

#4070 feat: pull in and convert vscode native html component definitions
  sites/site-utilities/package.json
  sites/site-utilities/src/definitions/native/div.definition.ts
  sites/site-utilities/src/definitions/native/heading.definition.ts
  sites/site-utilities/src/definitions/native/html-native.definition.ts
  sites/site-utilities/src/definitions/native/html-native.vs-code-v1.1-types.ts
  sites/site-utilities/src/definitions/native/image.definition.ts
  sites/site-utilities/src/definitions/native/index.ts
  sites/site-utilities/src/definitions/native/label.definition.ts
  sites/site-utilities/src/definitions/native/paragraph.definition.ts
  sites/site-utilities/src/definitions/native/span.definition.ts
  sites/site-utilities/src/definitions/native/style.definition.ts
  yarn.lock
Labels: area:tools

#4110 fix: flipper icon and menu item text in high contrast mode
  packages/web-components/fast-components/src/flipper/flipper.styles.ts
  packages/web-components/fast-components/src/menu-item/menu-item.styles.ts
Labels: area:fast-components, bug

#4108 fix: revert radio to using class selector instead of attr, update slider-label to use internal styles for orientation
  packages/web-components/fast-components/docs/api-report.md
  packages/web-components/fast-components/src/radio/radio.styles.ts
  packages/web-components/fast-components/src/slider-label/index.ts
  packages/web-components/fast-components/src/slider-label/slider-label.styles.ts
  packages/web-components/fast-foundation/docs/api-report.md
  packages/web-components/fast-foundation/src/radio/radio.ts
  packages/web-components/fast-foundation/src/slider-label/slider-label.ts
Labels: area:fast-components, area:fast-foundation

#4103 chore: add operations scripts for maintaining infrastructure
  build/operations/README.md
  build/operations/azure.ini
  build/operations/config.sh
  build/operations/diagrams/app-service-reference-architectures.vsdx
  build/operations/diagrams/consistent-management-layer.png
  build/operations/diagrams/multi-region-web-app-diagram.png
  build/operations/docs/testing.md
  build/operations/functions.sh
  build/operations/inputs.sh
  build/operations/recipes/create.sh
  build/operations/recipes/debug.sh
  build/operations/recipes/delete.sh
  build/operations/recipes/deploy.sh
  build/operations/recipes/login.sh
  build/operations/recipes/logout.sh
  build/operations/services/create-app.sh
  build/operations/services/create-appi.sh
  build/operations/services/create-asp.sh
  build/operations/services/create-cdn.sh
  build/operations/services/create-dns.sh
  build/operations/services/create-fd.sh
  build/operations/services/create-kv.sh
  build/operations/services/create-log.sh
  build/operations/services/create-rg.sh
  build/operations/services/create-st.sh
  build/operations/services/delete-rg.sh
  sites/static/assets/fast-logo-test.png
  sites/static/server.js
Labels: area:cloud, area:dev-ops, chore

#4135 fix: update high contrast colors in button and anchor components
  packages/web-components/fast-components/src/button/button.styles.ts
  packages/web-components/fast-components/src/styles/patterns/button.ts
Labels: area:fast-components
