Repository microsoft/fast, pull requests merged in 2021-11, with the labels that each got.

#5362 update workflows for consistency to match new implementations on new repositories
  .github/workflows/cd-color-stage.yml
  .github/workflows/cd-explore-stage.yml
  .github/workflows/cd-publish.yml
  .github/workflows/cd-static-cdn.yml
  .github/workflows/cd-www-stage.yml
  .github/workflows/ci-daily.yml
  .github/workflows/ci-weekly.yml
Labels: area:dev-ops

#5364 add pr testing for documentation
  .github/workflows/azure-static-web-apps-purple-ocean-0b7ce3410.yml
  .github/workflows/cd-www-stage.yml
Labels: area:dev-ops, area:cloud

#5365 add pr testing for component explorer
  .github/workflows/azure-static-web-apps-blue-coast-0df7a6610.yml
  .github/workflows/cd-explore-stage.yml
Labels: area:dev-ops, area:cloud

#5366 add pr testing for color explorer
  .github/workflows/cd-color-stage.yml
Labels: area:dev-ops, area:cloud

#5367 update badges for new workflows
  README.md
Labels: area:dev-ops

#5375 remove autogenerated workflow
  .github/workflows/azure-static-web-apps-purple-sand-03fe10e10.yml
Labels: area:dev-ops

#5396 chore: visual refresh on card component
  packages/web-components/fast-components/src/card/card.styles.ts
  packages/web-components/fast-components/src/styles/elevation.ts
Labels: area:fast-components

#5405 chore: visual refresh on flipper component
  packages/web-components/fast-components/src/flipper/flipper.styles.ts
  packages/web-components/fast-components/src/flipper/index.ts
Labels: area:fast-components

#5393 chore: visual refresh on breadcrumb item component
  packages/web-components/fast-components/src/breadcrumb-item/breadcrumb-item.styles.ts
  packages/web-components/fast-components/src/breadcrumb-item/fixtures/base.html
Labels: area:fast-components

#5400 chore: visual refresh on checkbox component
  packages/web-components/fast-components/src/checkbox/checkbox.styles.ts
  packages/web-components/fast-components/src/checkbox/fixtures/base.html
  packages/web-components/fast-components/src/checkbox/index.ts
  packages/web-components/fast-components/src/design-tokens.ts
Labels: area:fast-components
