Repository microsoft/fast, pull requests merged in 2021-04, with the labels that each got.

#4513 chore: update ci weekly with pull request to master trigger
  .github/workflows/ci-weekly.yml
Labels: area:dev-ops, chore

#3896 chore: update issue and PR templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/report-a-bug.md
  .github/ISSUE_TEMPLATE/request-a-feature.md
  .github/ISSUE_TEMPLATE/rfc.md
  .github/pull_request_template.md
Labels: status:blocked

#4559 Added --access public to unblocked denied access to npm registry
  .github/workflows/cd-publish.yml
Labels: area:dev-ops

#4572 update helmet version to improve security and take on CSP patches
  sites/site-utilities/statics/server/package.json
  sites/site-utilities/statics/server/server.js
Labels: area:cloud

#4578 fix: add -r to publish and set node-path to true
  .github/workflows/cd-publish.yml
  .npmrc
Labels: area:dev-ops

#4585 add default registry url with updated npm token
  .github/workflows/cd-publish.yml
Labels: area:dev-ops

#4567 chore: update yarn.lock file
  yarn.lock
Labels: area:dev-ops

#4588 update to new service account
  .github/workflows/cd-publish.yml
  package.json
Labels: area:dev-ops

#4590 add token to publish command
  .github/workflows/cd-publish.yml
Labels: area:dev-ops

#4611 fix: add separator on breadcrumb-item when a new item is added
  change/@microsoft-fast-components-b941cce6-aad9-473d-bc4e-0b03c92661e6.json
  change/@microsoft-fast-foundation-efa3c97d-df28-4674-b07f-e81ff8d2b3b2.json
  packages/web-components/fast-components/src/breadcrumb-item/breadcrumb-item.styles.ts
  packages/web-components/fast-components/src/breadcrumb/breadcrumb.stories.ts
  packages/web-components/fast-components/src/breadcrumb/fixtures/base.html
  packages/web-components/fast-foundation/src/breadcrumb/breadcrumb.ts
Labels: bug

#4637 fix: resolved react-dev-utils and is-svg
  yarn.lock
Labels: area:cloud, area:dev-ops
