Repository microsoft/fast, pull requests merged in 2021-06, with the labels that each got.

#4783 update lodash@^4.17.21:, dns-packet@^1.34: through dependencies resol…
  package.json
  yarn.lock
Labels: area:dev-ops

#4823 fix: removed background plate on hover and active states on lightweight and hypertext anchor
  change/@microsoft-fast-components-6ea330cd-b126-498e-a706-28b06496c3f8.json
  packages/web-components/fast-components/src/styles/patterns/button.ts
Labels: area:fast-components, bug

#4863 fix: update trim-newlines, glob-parent
  yarn.lock
Labels: area:dev-ops

#4873 fix: update moderate severity security
  package.json
  yarn.lock
Labels: area:dev-ops

#4894 fixed: high contrast pass to fix missing and wrong forced color keywords
  packages/web-components/fast-components/src/accordion-item/accordion-item.styles.ts
  packages/web-components/fast-components/src/breadcrumb-item/breadcrumb-item.styles.ts
  packages/web-components/fast-components/src/button/button.styles.ts
  packages/web-components/fast-components/src/menu-item/menu-item.styles.ts
  packages/web-components/fast-components/src/number-field/number-field.styles.ts
  packages/web-components/fast-components/src/radio/radio.styles.ts
  packages/web-components/fast-components/src/styles/patterns/button.ts
  packages/web-components/fast-components/src/tab/tab.styles.ts
  packages/web-components/fast-components/src/text-field/text-field.styles.ts
Labels: area:fast-components, bug

#4849 update csp for images hosted on placehold.it
  sites/site-utilities/statics/server/server.js
Labels: area:cloud, area:dev-ops, chore

#4918 Fixed foregroundOnAccent recipe to work in all states
  change/@microsoft-fast-components-630efb7a-0f90-42a0-9246-67d766f3e16d.json
  packages/web-components/fast-components/docs/api-report.md
  packages/web-components/fast-components/src/checkbox/checkbox.styles.ts
  packages/web-components/fast-components/src/color/recipes/accent-fill.spec.ts
  packages/web-components/fast-components/src/color/recipes/accent-fill.ts
  packages/web-components/fast-components/src/design-tokens.ts
  packages/web-components/fast-components/src/disclosure/disclosure.styles.ts
  packages/web-components/fast-components/src/flipper/flipper.styles.ts
  packages/web-components/fast-components/src/listbox-option/listbox-option.styles.ts
  packages/web-components/fast-components/src/radio/radio.styles.ts
  packages/web-components/fast-components/src/select/select.styles.ts
  packages/web-components/fast-components/src/styles/patterns/button.ts
  packages/web-components/fast-components/src/switch/switch.styles.ts
Labels: area:fast-components
