Repository microsoft/fast, pull requests merged in 2021-03, with the labels that each got.

#4205 fix: add radio and checkbox visual in fast-menu-item
  packages/web-components/fast-components/src/menu-item/menu-item.styles.ts
  packages/web-components/fast-components/src/menu/fixtures/menu.html
  packages/web-components/fast-foundation/src/menu-item/menu-item.template.ts
Labels: area:fast-components, bug

#4448 feat: add ability to hide step controls and update reveal on hover and focus-within
  packages/web-components/fast-components/src/number-field/fixtures/number-field.html
  packages/web-components/fast-components/src/number-field/number-field.definition.ts
  packages/web-components/fast-components/src/number-field/number-field.styles.ts
  packages/web-components/fast-foundation/docs/api-report.md
  packages/web-components/fast-foundation/src/number-field/number-field.spec.ts
  packages/web-components/fast-foundation/src/number-field/number-field.template.ts
  packages/web-components/fast-foundation/src/number-field/number-field.ts
Labels: area:fast-components, area:fast-foundation

#4464 fix: ensure button font size and line height map to design system properties
  packages/web-components/fast-components/src/styles/patterns/button.ts
Labels: area:fast-components, area:fast-foundation

#4487 chore: update beachball configuration and testing
  .github/workflows/ci-daily.yml
  .github/workflows/ci-nightly.yml
  .npmrc
  build/releasing/customRenderers.ts
  package.json
  yarn.lock
Labels: area:dev-ops

#4480 fix: update react-dev-utils to 11.0.4 & is-svg@^4.2.2:
  yarn.lock
Labels: area:dev-ops

#4496 chore: update font to use cdn for security enhancement
  sites/fast-creator/app/index.tsx
  sites/site-utilities/src/components/editor/editor.style.css
Labels: area:cloud

#4499 fix: addresses an issue in the windows cross browser testing where scenarios were not found
  sites/fast-component-explorer/package.json
Labels: area:dev-ops

#4511 chore:Disable-beachball publish on ci-nightly for now
  .github/workflows/ci-nightly.yml
Labels: area:dev-ops
