Repository microsoft/fast, pull requests merged in 2021-05, with the labels that each got.

#4619 fix: removed disabled style on anchor web component
  change/@microsoft-fast-components-b6b4bb43-235c-49bf-bd34-b8c73e11ef47.json
  packages/web-components/fast-components/src/button/button.styles.ts
  packages/web-components/fast-components/src/styles/patterns/button.ts
Labels: area:fast-components

#4691 update handlebars to resolve security vulnerability
  yarn.lock
Labels: area:dev-ops

#4722 update to exclude tooling from beachball publishing
  build/releasing/index.ts
Labels: area:dev-ops

#4745 split playwright steps in PR actions
  .github/workflows/ci-weekly.yml
  change/@microsoft-fast-components-7ed967b6-eff5-4071-ab45-ea6f05c428da.json
  packages/web-components/fast-components/__test__/harness.js
  packages/web-components/fast-components/package.json
  yarn.lock
Labels: area:dev-ops, chore
