Repository microsoft/fast, pull requests merged in 2022-01, with the labels that each got.

#5534 chore(deps): Update lockfile resolutions for packages identified by dependabot
  yarn.lock
Labels: compliance:security, dependencies

#5330 Added accent and neutral base color attributes to the design system provider
  change/@microsoft-fast-components-f8ddb38a-4380-4383-a6b3-7e1b02feed9c.json
  packages/web-components/fast-components/docs/api-report.md
  packages/web-components/fast-components/src/color/utilities/color-constants.ts
  packages/web-components/fast-components/src/design-system-provider/design-system-provider.vscode.definition.json
  packages/web-components/fast-components/src/design-system-provider/index.ts
  packages/web-components/fast-components/src/design-tokens.ts
  sites/site-utilities/statics/assets/components/fast-design-system-provider.schema.json
Labels: area:fast-components

#5546 set network timeout for yarn install from 0.6min to 6min
  .github/workflows/ci-validate-platforms.yml
Labels: area:dev-ops

#5541 update node-fetch to at least 2.6.7 to fix security vulnerability
  yarn.lock
Labels: area:dev-ops, compliance:security, dependencies
